/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-04-12 16:07:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import BD.ConexionBD;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("BD.ConexionBD");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <title></title>\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"Styles/mainStyles.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"Js/jquery-ui-1.12.1.custom/jquery-ui.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"Js/jquery-ui-1.12.1.custom/jquery-ui.min.css\">\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"Js/jquery-ui-1.12.1.custom/santiago.datepicker.css\">\n");
      out.write("        <script src=\"Js/jquery-3.3.1.min.js\"></script>\n");
      out.write("        <script src=\"Js/jquery-ui-1.12.1.custom/jquery-ui.js\"></script>\n");
      out.write("        <script src=\"Js/jquery-ui-1.12.1.custom/jquery-ui.min.js\"></script>\n");
      out.write("        <script src=\"Js/jsController.js\"></script>\n");
      out.write("        <script src=\"Js/alerts.js\"></script>\n");
      out.write("        <script src=\"Js/funcionesRegistros.js\"></script>\n");
      out.write("\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"/>\n");
      out.write("    </head>\n");
      out.write("    <div class=\"bar-title\">\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("        <img class=\"icons-bar-title\" onmouseout=\"this.src = 'Icons/salir.svg';\" onmouseover=\"this.src = 'Icons/salir2.svg';\"\n");
      out.write("             src=\"Icons/salir.svg\" style=\"width: 20px; height: 20px; margin: 11px; float: right; cursor: pointer; \">\n");
      out.write("\n");
      out.write("        <img class=\"icons-bar-title\" onmouseout=\"this.src = 'Icons/user.svg';\" onmouseover=\"this.src = 'Icons/user2.svg';\"\n");
      out.write("             src=\"Icons/user.svg\" style=\"width: 20px; height: 20px; margin: 11px; float: right; cursor: pointer; \">\n");
      out.write("        <img class=\"icons-bar-title\" onmouseout=\"this.src = 'Icons/bell.svg';\" onmouseover=\"this.src = 'Icons/bell2.svg';\"\n");
      out.write("             src=\"Icons/bell.svg\" style=\"width: 20px; height: 20px; margin: 11px; float: right; cursor: pointer;\">\n");
      out.write("        <p>Jeisson Hernandez</p>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"bar-menu\">\n");
      out.write("\n");
      out.write("        <div class=\"menu-bttn-toggle\">\n");
      out.write("\n");
      out.write("            <div class=\"bttn-toggle\" onclick=\"moviemientoMenu()\" >\n");
      out.write("\n");
      out.write("                <div class=\"bar-1\" ></div>\n");
      out.write("                <div class=\"bar-2\" ></div>\n");
      out.write("                <div class=\"bar-3\" ></div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <div class=\"menu-list-title\">\n");
      out.write("            MENU\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <ul class=\"list-menu\">\n");
      out.write("            <li id=\"pagInicio\" class=\"btn\">\n");
      out.write("                <img src=\"Icons/home.svg\" style=\"width: 20px; height: 20px;vertical-align: middle; float: left;\" class=\"home-img\">\n");
      out.write("                &nbsp;&nbsp;&nbsp; <span class=\"menu-name\">INICIO</span>\n");
      out.write("            </li>\n");
      out.write("            <li id=\"pagRegistros\" class=\"btn\" onclick=\"cargarPagina(this.id);onFocus('tbRegistros');\" >\n");
      out.write("                <img src=\"Icons/address-book.svg\" style=\"width: 20px; height: 20px;vertical-align: middle;float: left;\"class=\"reg-img\">\n");
      out.write("                &nbsp;&nbsp;&nbsp; <label class=\"menu-name\" >REGISTROS</label>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </li>\n");
      out.write("            <li id=\"pagAcademico\" class=\"btn\"onclick=\"cargarPagina(this.id)\">\n");
      out.write("                <img src=\"Icons/book.svg\" style=\"width: 20px; height: 20px;vertical-align: middle;float: left;\" class=\"aca-img\">\n");
      out.write("                &nbsp;&nbsp;&nbsp;\n");
      out.write("                <span class=\"menu-name\">ACADEMICO</span></li>\n");
      out.write("            <li id=\"pagDocentes\" class=\"btn\">\n");
      out.write("                <img src=\"Icons/chalkboard-teacher.svg\" style=\"width: 20px; height: 20px;vertical-align: middle;float: left;\" class=\"doc-img\">\n");
      out.write("                &nbsp;&nbsp;&nbsp;\n");
      out.write("                <span class=\"menu-name\">DOCENTES</span> </li>\n");
      out.write("\n");
      out.write("        </ul>\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("    <div class=\"div-tabs\" hidden>\n");
      out.write("        <div id=\"tbInicio\" tabindex=\"0\" onclick=\"onFocus(this.id)\" class=\"page-tabs tab-inicio\" >\n");
      out.write("            Inicio\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"tbRegistros\" tabindex=\"0\" onclick=\"onFocus(this.id)\" class=\"page-tabs tab-registros\" hidden>\n");
      out.write("            Registros\n");
      out.write("\n");
      out.write("            <img onclick=\"closeTabReg('tab-registros')\" src=\"Icons/close.svg\" style=\"width: 15px; height: 15px; margin: 5px; margin-right: 7px; float: right; cursor: pointer;\">\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div id=\"tbAcademico\" onclick=\"onFocus(this.id)\"  tabindex=\"0\" class=\"page-tabs tab-academico\" hidden>\n");
      out.write("            Academico\n");
      out.write("\n");
      out.write("            <img onclick=\"closeTabReg('tab-academico')\" src=\"Icons/close.svg\" style=\"width: 15px; height: 15px; margin: 5px; margin-right: 7px; float: right; cursor: pointer;\">\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div id=\"loadRegistros\" class=\"pageLoader-registros\">\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"pageLoader-academico\">\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"pageLoader-docentes\">\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"modal-confirm-form\">\n");
      out.write("        <div id=\"draggable\" class=\"confirm-info\" >\n");
      out.write("            <p class=\"modal-tittle\" ><img src=\"Icons/advertencia.svg\" style=\"width: 50px; height: 50px; margin-right:   20px; margin-top: 4px; vertical-align: middle\" >Advertencia</p>\n");
      out.write("            <p class=\"modal-sub-title\">¿Seguro que desea continuar?</p>\n");
      out.write("            <fieldset>\n");
      out.write("\n");
      out.write("                los datos dados no se podran modificar hasta finalizar todo el proceso de registro. Asegurese que la información dada sea correcta antes\n");
      out.write("                de continuar.\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("\n");
      out.write("                <div class=\"bttn-confirm-form-student\">\n");
      out.write("                    <button class=\"bttn-not-confirm\" onclick=\"closeModalForm()\" >NO</button>\n");
      out.write("                    <button class=\"bttn-yes-confirm\" onclick=\"sendFormStudent()\">SI</button>\n");
      out.write("                </div>\n");
      out.write("            </fieldset>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    $(function() {\n");
      out.write("        $(\"#draggable\").draggable({containment: \"parent\"});\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\".list-menu .btn\").click(function() {\n");
      out.write("        $(\".home-img\").attr(\"src\", \"Icons/home.svg\");\n");
      out.write("        $(\".reg-img\").attr(\"src\", \"Icons/address-book.svg\");\n");
      out.write("        $(\".aca-img\").attr(\"src\", \"Icons/book.svg\");\n");
      out.write("        $(\".doc-img\").attr(\"src\", \"Icons/chalkboard-teacher.svg\");\n");
      out.write("\n");
      out.write("\n");
      out.write("        $(\".list-menu .btn\").removeClass('active');\n");
      out.write("        $(this).toggleClass('active');\n");
      out.write("        var getIdButton = $(this).attr('id');\n");
      out.write("        alertError(getIdButton);\n");
      out.write("\n");
      out.write("        if (getIdButton === \"pagRegistros\") {\n");
      out.write("            $(\".reg-img\").attr(\"src\", \"Icons/address-book-hover.svg\");\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        if (getIdButton === \"pagInicio\") {\n");
      out.write("            $(\".home-img\").attr(\"src\", \"Icons/home-hover.svg\");\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        if (getIdButton === \"pagDocentes\") {\n");
      out.write("            $(\".doc-img\").attr(\"src\", \"Icons/chalkboard-teacher-hover.svg\");\n");
      out.write("        }\n");
      out.write("\n");
      out.write("        if (getIdButton === \"pagAcademico\") {\n");
      out.write("            $(\".aca-img\").attr(\"src\", \"Icons/book-hover.svg\");\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    });\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
