/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-04-18 23:33:24 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Modulos;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DAO.RespuestaDAO;
import VO.PruebaVO;
import java.util.ArrayList;
import DAO.PruebaDAO;
import DAO.PreguntaPruebaDAO;

public final class editarModulos_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.RespuestaDAO");
    _jspx_imports_classes.add("DAO.PreguntaPruebaDAO");
    _jspx_imports_classes.add("VO.PruebaVO");
    _jspx_imports_classes.add("DAO.PruebaDAO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<section class=\"modify-answers\">\n");
      out.write("    <form   id=\"formRegistrarPregunta\"  enctype=\"multipart/form-data\"  method=\"post\" >\n");
      out.write("        <section class=\"modify-answers__section\">\n");
      out.write("            <fieldset class=\"form-container__fieldset\">\n");
      out.write("                <legend class=\" form-container__legend\">Pregunta</legend>\n");
      out.write("\n");
      out.write("                <label for=\"prueba\" >Seleccione la prueba</label>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <select id=\"prueba\" class=\"\" name=\"pruebaCodigo\" required>\n");
      out.write("                    <option value=\"\" disabled selected>Seleccione...</option>             \n");
      out.write("                    ");
 PruebaDAO prdao = new PruebaDAO();
                        ArrayList<PruebaVO> pruebas = prdao.obetenerPruebas();
                        for (PruebaVO prueba : pruebas) {
                    
      out.write("  \n");
      out.write("                    <option value=\"");
      out.print(prueba.getPRUE_CODIGO());
      out.write('"');
      out.write('>');
      out.print(prueba.getPRUE_NOMBRE());
      out.write("</option> \n");
      out.write("                    ");

                        }
                    
      out.write("\n");
      out.write("\n");
      out.write("                </select>\n");
      out.write("                <br>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"primerTexto\">Texto Pregunta</label>\n");
      out.write("                <br><br>\n");
      out.write("                <textarea class=\"modify-answers__txtarea\" placeholder=\"Ingrese aqui el texto\" name=\"primerTexto\" required></textarea>\n");
      out.write("                <br><br>  \n");
      out.write("                <p>¿Desea Agregar una imagen a la pregunta?</p>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"val1\"> Si</label>\n");
      out.write("                <input type=\"radio\" id=\"val1\" onclick=\"agregarImagenPregunta(this.value)\" name=\"validacionImagen\" value=\"1\" />\n");
      out.write("                <label for=\"val0\"> No</label>\n");
      out.write("                <input type=\"radio\" id=\"val0\" onclick=\"agregarImagenPregunta(this.value)\" name=\"validacionImagen\" value=\"0\" checked />\n");
      out.write("                <br><br>\n");
      out.write("                <div class=\"modify-answers__upload\" id=\"divUploadImagen\" hidden>\n");
      out.write("                    <label for=\"imagenPregunta\" id=\"labelImagenPregunta\" class=\"btn\" >Seleccionar Imagen <b>(Formato .JPG)</b> </label>\n");
      out.write("                    <br>\n");
      out.write("                    <br>\n");
      out.write("                    <input accept=\"image/png,image/jpeg\" type=\"file\" id=\"imagenPregunta\" name=\"imagenPregunta\" />\n");
      out.write("                </div>\n");
      out.write("                <div id=\"textoDespuesImagen\" hidden>\n");
      out.write("                    <br><br>\n");
      out.write("                    <label for=\"segundoTexto\">Texto despues de imagen</label>\n");
      out.write("                    <br><br>\n");
      out.write("                    <textarea class=\"modify-answers__txtarea\" placeholder=\"Ingrese aqui el texto\" name=\"segundoTexto\"></textarea>\n");
      out.write("                </div>\n");
      out.write("                <input type=\"text\" name=\"modulo\" value=\"guardarImagenPregunta\" hidden>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            </fieldset> \n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section class=\"modify-answers__section\">\n");
      out.write("            <fieldset class=\"form-container__fieldset\"> \n");
      out.write("                <legend class=\"form-container__legend\" >Opcciones de respuesta</legend>\n");
      out.write("                <p>¿ Como desea el contenido de las opciones de respuesta?</p>\n");
      out.write("                <br>\n");
      out.write("                <label for=\"val1\"> Solo Texto</label>\n");
      out.write("                <input type=\"radio\" id=\"val1\" onclick=\"agregarImagenRespuesta(this.value)\" name=\"validacionImagenRespuestas\" value=\"1\" checked />\n");
      out.write("                <label for=\"val0\"> Texto e Imagen</label>\n");
      out.write("                <input type=\"radio\" id=\"val0\" onclick=\"agregarImagenRespuesta(this.value)\" name=\"validacionImagenRespuestas\" value=\"0\" />\n");
      out.write("                <br><br>\n");
      out.write("                <label for=\"respuesta1\">Respuesta 1</label>\n");
      out.write("                <br><br>\n");
      out.write("                <textarea required id=\"respuesta1\"  class=\"modify-answers__txtarea modify-answers__txtarea--answer\" placeholder=\"Ingrese aqui el texto\" name=\"respuesta1\"></textarea> \n");
      out.write("                <br>\n");
      out.write("                <div class=\"modify-answers__upload\" id=\"divUploadImagenRespuesta1\" hidden>\n");
      out.write("                    <label for=\"imagenPregunta\" id=\"labelimagenRespuesta1\" class=\"btn\" >Seleccionar Imagen <b>(Formato .JPG)</b> </label>\n");
      out.write("                    <br>\n");
      out.write("                    <br>\n");
      out.write("                    <input type=\"file\" class=\"modify-answers__imgfile\" id=\"imagenRespuesta1\" name=\"imagenRespuesta1\"   />\n");
      out.write("                </div>\n");
      out.write("                <br><br>\n");
      out.write("                <label for=\"respuesta2\">Respuesta 2</label>\n");
      out.write("                <br><br>\n");
      out.write("                <textarea  required id=\"respuesta2\"  class=\"modify-answers__txtarea modify-answers__txtarea--answer\" placeholder=\"Ingrese aqui el texto\" name=\"respuesta2\"></textarea> \n");
      out.write("                <br>\n");
      out.write("                <div class=\"modify-answers__upload\" id=\"divUploadImagenRespuesta2\" hidden>\n");
      out.write("                    <label for=\"imagenPregunta\" id=\"labelimagenRespuesta2\" class=\"btn\" >Seleccionar Imagen <b>(Formato .JPG)</b> </label>\n");
      out.write("                    <br>\n");
      out.write("                    <br>\n");
      out.write("                    <input type=\"file\" class=\"modify-answers__imgfile\" id=\"imagenRespuesta2\" name=\"imagenRespuesta2\" />\n");
      out.write("                </div>\n");
      out.write("                <br><br>\n");
      out.write("                <label for=\"respuesta3\">Respuesta 3</label>\n");
      out.write("                <br><br>\n");
      out.write("                <textarea required id=\"respuesta3\"  class=\"modify-answers__txtarea modify-answers__txtarea--answer\" placeholder=\"Ingrese aqui el texto\" name=\"respuesta3\"></textarea> \n");
      out.write("                <br>\n");
      out.write("                <div class=\"modify-answers__upload\" id=\"divUploadImagenRespuesta3\" hidden>\n");
      out.write("                    <label for=\"imagenPregunta\" id=\"labelimagenRespuesta3\" class=\"btn\" >Seleccionar Imagen <b>(Formato .JPG)</b> </label>\n");
      out.write("                    <br>\n");
      out.write("                    <br>\n");
      out.write("                    <input type=\"file\" id=\"imagenRespuesta3\" class=\"modify-answers__imgfile\"  name=\"imagenRespuesta3\"/>\n");
      out.write("                </div>\n");
      out.write("                <br><br>\n");
      out.write("                <label for=\"respuestaCorrecta\">Respuesta Correcta</label>\n");
      out.write("                <br><br>\n");
      out.write("                <textarea required id=\"respuesta4\"  class=\"modify-answers__txtarea modify-answers__txtarea--answer\" placeholder=\"Ingrese aqui el texto\" name=\"respuesta4\"></textarea> \n");
      out.write("                <br>\n");
      out.write("                <div class=\"modify-answers__upload\" id=\"divUploadImagenRespuesta4\" hidden>\n");
      out.write("                    <label for=\"imagenPregunta\" id=\"labelimagenRespuesta4\" class=\"btn\" >Seleccionar Imagen <b>(Formato .JPG)</b> </label>\n");
      out.write("                    <br>\n");
      out.write("                    <br>\n");
      out.write("                    <input type=\"file\" id=\"imagenRespuesta4\" class=\"modify-answers__imgfile\"  name=\"imagenRespuesta4\"  />\n");
      out.write("                </div>\n");
      out.write("                <br>\n");
      out.write("                <button type=\"submit\">Guardar Pregunta</button>\n");
      out.write("            </fieldset>\n");
      out.write("        </section>\n");
      out.write("    </form>\n");
      out.write("</section>\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    $(\"#formRegistrarPregunta\").on(\"submit\", function (e) {\n");
      out.write("\n");
      out.write("        var f = $(this);\n");
      out.write("        var formulario = $(\"#formRegistrarPregunta\")[0];\n");
      out.write("        var formData = new FormData(formulario);\n");
      out.write("        for (var value of formData.values()) {\n");
      out.write("            console.log(value);\n");
      out.write("        }\n");
      out.write("        e.preventDefault();\n");
      out.write("        $.ajax({\n");
      out.write("            url: 'ModulosController',\n");
      out.write("            type: 'POST',\n");
      out.write("            dataType: \"html\",\n");
      out.write("            data: formData,\n");
      out.write("            cache: false,\n");
      out.write("            contentType: false,\n");
      out.write("            processData: false,\n");
      out.write("            success: function (r) {\n");
      out.write("                alertSucsses(\"¡Pregunta guardada con exito!\");\n");
      out.write("                 $(\"#formRegistrarPregunta\")[0].reset();\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"#imagenPregunta\").change(function () {\n");
      out.write("        var name = $(\"#imagenPregunta\").val();\n");
      out.write("        var nombre = name.split('\\\\');\n");
      out.write("        var formato = nombre[2].split(\".\");\n");
      out.write("        if (formato[1] === \"jpg\" || formato[1] === \"JPG\") {\n");
      out.write("            alertSucsses(\"Imagen cargada con exito\");\n");
      out.write("        } else {\n");
      out.write("            alertWarining(\"El formato de la imagen debe ser JPG\");\n");
      out.write("            document.getElementById(\"imagenPregunta\").value = '';\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\".modify-answers__imgfile\").change(function () {\n");
      out.write("        var name = $(\"#\" + this.id).val();\n");
      out.write("        var nombre = name.split('\\\\');\n");
      out.write("        var formato = nombre[2].split(\".\");\n");
      out.write("        if (formato[1] === \"jpg\" || formato[1] === \"JPG\") {\n");
      out.write("            alertSucsses(\"Imagen cargada con exito\");\n");
      out.write("        } else {\n");
      out.write("            alertWarining(\"El formato de la imagen debe ser JPG\");\n");
      out.write("            document.getElementById(this.id).value = '';\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
