/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-01-04 16:10:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Vista.VistaSecretaria;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Modelo.MetodosAlumno;

public final class Registros_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Modelo.MetodosAlumno");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("     <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\n");
      out.write("     <meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\" />\n");
      out.write("        <link rel=\"stylesheet\" href=\"Estilos/EstilosRegistro.css\">\n");
      out.write("         <script type=\"text/javascript\"  src=\"Js/FunctionsPaginaPrincipalSec.js\"></script>\n");
      out.write("         <script type=\"text/javascript\" src=\"Js/MetodosAjaxRegistros.js\"></script>\n");
      out.write("           <script src=\"//code.jquery.com/jquery-1.12.0.min.js\"></script>\n");
      out.write("        <title>Registros </title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <div class=\"datos\">\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("        <div class=\"BotonesReg\"> \n");
      out.write("        \n");
      out.write("            <button class=\"Btn\" type=\"button\" onclick=\"verFomulario()\">Estudiante</button>\n");
      out.write("            <button  class=\"Btn\" type=\"button\" onclick=\"verFomularioDoc()\">Planta Academica</button>\n");
      out.write("               <button  class=\"Btn\" type=\"button\" onclick=\"verFomularioFun()\">Funcionarios</button>\n");
      out.write("        </div>\n");
      out.write("        <hr style=\"background: #3066b3;height: 4px; \">\n");
      out.write("        <div class=\"FomularioEstu\">\n");
      out.write("            <form class=\"DatosEstudiante\">\n");
      out.write("            <table>\n");
      out.write("                  <tr>\n");
      out.write("                        <td class=\"Titulos\">DATOS DEL ALUMNO</td>\n");
      out.write("                    </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Primer Nombre</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"PrimNom\" required></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Segundo Nombre</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"SegNom\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Primer Apellido</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"PrimApe\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Segundo Apellido</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"SegApe\"></td>\n");
      out.write("                </tr>                \n");
      out.write("                   <tr>\n");
      out.write("                <td>Genero</td>\n");
      out.write("                <td><select class=\"Slct\" name=\"Gen\"> \n");
      out.write("                        <option>Masculino</option>\n");
      out.write("                        <option>Femenino</option>\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Fecha De Nacimiento</td>\n");
      out.write("                <td><input type=\"date\" class=\"inp\" name=\"FecNaci\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Departamento de Nacimiento</td>\n");
      out.write("                <td><select class=\"Slct\"  name=\"DepNac\" onchange=\"idDep(this.value)\">\n");
      out.write("                        ");
 Modelo.MetodosAlumno ma = new MetodosAlumno();
                       out.println(ma.llenarSelectDep());
                        
      out.write("\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Ciudad De Nacimiento</td>\n");
      out.write("                <td><select class=\"Slct\" id=\"mun\" name=\"CiuNac\"><option>Seleccionar</option></select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Cantidad De Hermanos</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"CanHrms\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Eps</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"Eps\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Tipo De Documento</td>\n");
      out.write("                <td><select class=\"Slct\" name=\"TipDoc\"> \n");
      out.write("                        <option>Tarjeta De Identidad</option>\n");
      out.write("                        <option>Cedula</option>\n");
      out.write("                        <option>Cedula De Extranjeria</option>\n");
      out.write("                        <option>Pasaporte</option>\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Numero De Documento</td>\n");
      out.write("                <td><input class=\"inp\" type=\"number\" name=\"NumDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Lugar De Expedicion</td>\n");
      out.write("                <td><select class=\"Slct\" name=\"LugExpDoc\">\n");
      out.write("                    ");
  out.println(ma.llenarSelecMunAll());   
      out.write("\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Fecha De Expedicion</td>\n");
      out.write("                <td><input type=\"date\" class=\"inp\" name=\"FecExpedicion\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Correo Electronico</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"Email\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Curso</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"Curso\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Departamento Actual</td>\n");
      out.write("                <td><select type=\"text\" class=\"Slct\" name=\"DepActual\" onchange=\"idDepActual(this.value)\">\n");
      out.write("                    ");
 out.println(ma.llenarSelectDep()); 
      out.write("\n");
      out.write("                    </select>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Ciudad Actual</td>\n");
      out.write("                <td><select class=\"Slct\"id=\"munAct\" name=\"CiuActual\"></select></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Barrio</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"Barrio\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Direccion Del Domicilio</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"DicDomicilio\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Estrato</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"Estrato\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td> Telefono Fijo</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"TelFijo\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td> Contraseña</td>\n");
      out.write("                <td><input type=\"password\" class=\"inp\" id=\"pass1\" name=\"pass1\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Confirme Contraseña</td>\n");
      out.write("                <td><input type=\"password\" class=\"inp\" id=\"pass2\" name=\"pass2\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td> <button type=\"button\" class=\"Btn\" onclick=\"nuevoAlumno()\">Guardar</button></td>\n");
      out.write("                                </tr>\n");
      out.write("                </table>\n");
      out.write("            \n");
      out.write("          \n");
      out.write("            <!-- DATOS DE LA MADRE ---------------- --> \n");
      out.write("             \n");
      out.write("                <table>\n");
      out.write("                      <tr>\n");
      out.write("                        <td class=\"Titulos\">DATOS DE LA MADRE</td>\n");
      out.write("                    </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td> Nombres</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"NomMadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Apellidos</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"ApeMadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Fecha De Nacimieyo</td>\n");
      out.write("                <td><input type=\"date\" class=\"inp\" name=\"FecNaciMadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Tipo De Documento</td>\n");
      out.write("                <td><select class=\"Slct\" name=\"TipDocMadre\"> \n");
      out.write("                        <option>Tarjeta De Identidad</option>\n");
      out.write("                        <option>Cedula</option>\n");
      out.write("                        <option>Cedula De Extranjeria</option>\n");
      out.write("                        <option>Pasaporte</option>\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Numero De Documento</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"NumDocMadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Ciudad Actual</td>\n");
      out.write("                <td><select class=\"Slct\" name=\"CiuActMadre\">\n");
      out.write("                    ");
 out.println(ma.llenarSelecMunAll()); 
      out.write("\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Barrio</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"BarrioMadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Direccion</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"DirMadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Estrato</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"EstratoMadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Telefono Fijo</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"TelFijoMadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Movil</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"MovilMadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("               \n");
      out.write("                <tr>\n");
      out.write("                <td>Ocupacion</td>\n");
      out.write("                        <td><select class=\"Slct\" name=\"OcupMadre\">                    \n");
      out.write("                                <option>Profesional</option>\n");
      out.write("                                <option>Ama De Casa</option>\n");
      out.write("                                <option>Empleada</option>\n");
      out.write("                                <option>Oficios Varios</option>\n");
      out.write("                                <option>Ninguna De Las Anteriores</option>\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("            </table>\n");
      out.write("        <!-- DATOS DEL PADRE ---------------- -->     \n");
      out.write("             \n");
      out.write("                \n");
      out.write("                <table>\n");
      out.write("                    <tr>\n");
      out.write("                        <td class=\"Titulos\">DATOS DEL PADRE</td>\n");
      out.write("                    </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td> Nombres</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"NomPadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Apellidos</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"ApePadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Fecha De Nacimieyo</td>\n");
      out.write("                <td><input type=\"date\" class=\"inp\" name=\"FecNaciPadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Tipo De Documento</td>\n");
      out.write("                <td><select class=\"Slct\" name=\"TipDocPadre\"> \n");
      out.write("                        <option>Tarjeta De Identidad</option>\n");
      out.write("                        <option>Cedula</option>\n");
      out.write("                        <option>Cedula De Extranjeria</option>\n");
      out.write("                        <option>Pasaporte</option>\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Numero De Documento</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"NumDocPadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Ciudad Actual</td>\n");
      out.write("                <td><select class=\"Slct\" name=\"CiuActPadre\">\n");
      out.write("                     ");
 out.println(ma.llenarSelecMunAll()); 
      out.write("\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Barrio</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"BarrioPadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Direccion</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"DirPadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                <td>Estrato</td>\n");
      out.write("                <td><input type=\"text\" class=\"inp\" name=\"EstratoPadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Telefono Fijo</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"TelFijoPadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                <td>Movil</td>\n");
      out.write("                <td><input type=\"number\" class=\"inp\" name=\"MovilPadre\"></td>\n");
      out.write("                </tr>\n");
      out.write("               \n");
      out.write("                <tr>\n");
      out.write("                <td>Ocupacion</td>\n");
      out.write("                        <td><select class=\"Slct\" name=\"OcupPadre\">                    \n");
      out.write("                                <option>Profesional</option>\n");
      out.write("                                <option>Amo De Casa</option>\n");
      out.write("                                <option>Empleado</option>\n");
      out.write("                                <option>Oficios Varios</option>\n");
      out.write("                                <option>Ninguna De Las Anteriores</option>\n");
      out.write("                    </select></td>\n");
      out.write("                </tr>\n");
      out.write("                \n");
      out.write("            </table>\n");
      out.write("            </form>\n");
      out.write("        </div>\n");
      out.write("        \n");
      out.write("        \n");
      out.write("        <div class=\"formDocente\">\n");
      out.write("            \n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                    <td class=\"Titulos\">Datos Del Docente</td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Primer Nombre</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"PrimNomDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Segundo Nombre</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"SegNomDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Primer Apellido</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"PrimApeDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Segundo Apellido</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"SegApeDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Fecha De Nacimiento</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"date\" name=\"FecNaciDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Departamento De Nacimiento</td>\n");
      out.write("                    <td> <select class=\"Slct\" name=\"DepNaciDoc\"></select></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Ciudad De Nacimiento</td>\n");
      out.write("                    <td> <select class=\"Slct\" name=\"CiuNaciDoc\"></select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Ciudad Actual</td>\n");
      out.write("                    <td>  <select class=\"Slct\" name=\"CiuActuDoc\"></select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Barrio</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"BarrioDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Direccion</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"DireccionDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Telefono</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"number\" name=\"TelDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Tipo De Documento</td>\n");
      out.write("                            <td> <select class=\"Slct\" name=\"TipoDoDoc\">\n");
      out.write("                                    \n");
      out.write("                           <option>Tarjeta De Identidad</option>\n");
      out.write("                        <option>Cedula</option>\n");
      out.write("                        <option>Cedula De Extranjeria</option>\n");
      out.write("                        <option>Pasaporte</option>\n");
      out.write("                        \n");
      out.write("                        </select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Numero De Documento</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"number\" name=\"NumDoDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Egresado De</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"EgreDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Licenciado En</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"LicDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("               \n");
      out.write("            </table>\n");
      out.write("            <table class=\"Asig\">\n");
      out.write("                  <tr>\n");
      out.write("                    <td>Años De Experiencia Laboral</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"number\" name=\"ExpLaboralDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Fecha De Ingreso: </td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"date\" name=\"FecIngreDoc\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                     <td class=\"Titulos\">Asignaturas A Dirigir</td>\n");
      out.write("                 </tr>\n");
      out.write("                  <tr>\n");
      out.write("                      <td></td>\n");
      out.write("                 </tr>\n");
      out.write("                 <tr>\n");
      out.write("                     <td> Ingles</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                 </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td> Matematicas</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                 </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td> Calculo</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                 </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td> Geometria</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                 </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td> Trigonometria </td><td><input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                 </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td> Socilaes</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                 </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td> Geografia </td><td><input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                 </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td> Etica </td><td><input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                 </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Religion </td><td><input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Filosofia</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Ciencias Politicas </td><td><input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Español </td><td><input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> C. Lectora </td><td><input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Edu. Fisica </td><td><input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Artes</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Musica</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Informatica </td><td><input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Tecnologia</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                    <td> Historia</td><td> <input class=\"inp\" type=\"checkbox\" name=\"CurDoc\"></td>\n");
      out.write("                    \n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                       <td> <button type=\"button\" class=\"Btn\"> Guardar</button></td>\n");
      out.write("                    <td></td>\n");
      out.write("                    <td></td>\n");
      out.write("                 \n");
      out.write("                    \n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("            \n");
      out.write("        <div class=\"formFuncionarios\">\n");
      out.write("            \n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                    <td  class=\"Titulos\">\n");
      out.write("                        Datos Del Funcionario\n");
      out.write("                    </td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Cargo</td>\n");
      out.write("                    <td><select class=\"Slct\" name=\"CargoFun\">\n");
      out.write("                                    <option>Secretaria</option>\n");
      out.write("                                    <option>Rector</option>\n");
      out.write("                                    <option>Otro</option>\n");
      out.write("                        </select></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Primer Nombre</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"PrimNomFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Segundo Nombre</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"SegNomFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Primer Apellido</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"PrimApeFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Segundo Apellido</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"SegApeFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Fecha De Nacimiento</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"date\" name=\"FecNaciFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Departamento De Nacimiento</td>\n");
      out.write("                    <td> <select class=\"Slct\" name=\"DepNaciFun\"></select></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Ciudad De Nacimiento</td>\n");
      out.write("                    <td> <select class=\"Slct\" name=\"CiuNaciFun\"></select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Ciudad Actual</td>\n");
      out.write("                    <td>  <select class=\"Slct\" name=\"CiuActuFun\"></select></td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            <table>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Barrio</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"BarrioFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Direccion</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"DireccionFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Telefono</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"number\" name=\"TelFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Tipo De Documento</td>\n");
      out.write("                            <td> <select class=\"Slct\" name=\"TipoDoFun\">\n");
      out.write("                                    \n");
      out.write("                           <option>Tarjeta De Identidad</option>\n");
      out.write("                        <option>Cedula</option>\n");
      out.write("                        <option>Cedula De Extranjeria</option>\n");
      out.write("                        <option>Pasaporte</option>\n");
      out.write("                        \n");
      out.write("                        </select></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Numero De Documento</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"number\" name=\"NumDoFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td>Egresado De</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"EgreFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Licenciado En</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"text\" name=\"LicFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("               \n");
      out.write("            </table>\n");
      out.write("            <table class=\"Asig\">\n");
      out.write("                  <tr>\n");
      out.write("                    <td>Años De Experiencia Laboral</td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"number\" name=\"ExpLaboralFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                 <tr>\n");
      out.write("                    <td>Fecha De Ingreso: </td>\n");
      out.write("                    <td> <input class=\"inp\" type=\"date\" name=\"FecIngreFun\"></td>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("                    <td><button type=\"button\"  class=\"Btn\">Guardar</button></td>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("            \n");
      out.write("       \n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
