/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-04-18 23:33:20 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DAO.InicioSesionDAO;
import DAO.DocenteDAO;
import DAO.AlumnoDAO;
import DAO.PersonaDAO;

public final class Principal_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.PersonaDAO");
    _jspx_imports_classes.add("DAO.DocenteDAO");
    _jspx_imports_classes.add("DAO.AlumnoDAO");
    _jspx_imports_classes.add("DAO.InicioSesionDAO");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

    if (session.getAttribute("sesion") == null) {
        response.sendRedirect("InicioSesion.jsp");
    } else {
        String PERS_ID = session.getAttribute("sesion").toString();
      out.write('\n');
  InicioSesionDAO indao = new InicioSesionDAO(); 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!doctype html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("\n");
      out.write("        <meta name=\"viewport\" content=\"width=450\" http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("\n");
      out.write("        <title>ASaber - Plataforma Educativa</title>\n");
      out.write("        <link rel=\"icon\" type=\"image/ico\" href=\"Images/Lo2.png\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"Styles/EstilosPrincipal.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"Styles/BasicStyles.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"Js/JQuery UI/jquery-ui.min.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"Js/JQuery UI/jquery-ui.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"Js/JQuery UI/jquery-ui.theme.css\"/>\n");
      out.write("        <link rel=\"stylesheet\" href=\"Js/JQuery UI/jquery-ui.structure.min.css\"/>\n");
      out.write("      \n");
      out.write("        <link rel=\"stylesheet\" href=\"Js/Trumbowyg-main/dist/ui/trumbowyg.min.css\"/>       \n");
      out.write("\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/jquery-3.6.0.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/Controlador.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/PaginaPrincipalControlador.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/registrosControlador.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/inicioSesionControlador.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/modulosControlador.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/pruebasControlador.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/resultadoControlador.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/busquedaUsuariosControlador.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/jquery.formdata.js \"></script>\n");
      out.write("     \n");
      out.write("       \n");
      out.write("      \n");
      out.write("\n");
      out.write("\n");
      out.write("        <script src=\"Js/JQuery UI/jquery-ui.min.js\"></script>\n");
      out.write("        <script src=\"Js/JQuery UI/jquery-ui.js\"></script>\n");
      out.write("        <script src=\"Js/JQuery UI/\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"Js/jqueryForms.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/alerts.js\"></script>\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("        <!-- INICIO DIV MAIN -->\n");
      out.write("        <div class=\"main-div\"> \n");
      out.write("            <!-- INICIO DIV MAIN__CONTAINER -->\n");
      out.write("            <div class=\"main-div__container\"></div> \n");
      out.write("            <!-- FIN DIV MAIN__CONTAINER -->\n");
      out.write("            <!-- INICIO DIV TOPBAR -->         \n");
      out.write("            <div class=\"top-div\"> \n");
      out.write("                <!-- INICIO DIV BOTON TOGGLE  -->\n");
      out.write("                <div class=\"top-div__bttn\" onclick=\" bttnMenu()\"> \n");
      out.write("                    <div class=\"top-div__bar1\"></div>  \n");
      out.write("                    <div class=\"top-div__bar2\"></div>  \n");
      out.write("                    <div class=\"top-div__bar3\" ></div> \n");
      out.write("                </div>\n");
      out.write("                <!-- FIN DIV BOTON TOGGLE  -->\n");
      out.write("                <!-- INICIO DIV MENU DESPLEGABLE  -->\n");
      out.write("                <div class=\"top-menu\">  \n");
      out.write("                    <div class=\"top-menu__profile\">\n");
      out.write("                        Perfil \n");
      out.write("                        <img  class=\"top-menu__icon top-menu__icon--profile\" src=\"Styles/Icons/perfil-icon.svg\" alt=\"alt\"/>\n");
      out.write("                    </div>\n");
      out.write("                    <div  class=\"top-menu__logout\" id=\"cerrarsesion\" onclick=\"cerrarSesion(this.id)\">\n");
      out.write("                        Cerrar Sesion \n");
      out.write("                        <img  class=\"top-menu__icon top-menu__icon--logout\" src=\"Styles/Icons/logout-icon.svg\" alt=\"alt\"/> \n");
      out.write("                    </div> \n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"top-menu__bttn \" onclick=\"openMenuDesp()\"> <!-- dropdown -->\n");
      out.write("                    <img  class=\"top-menu__icon--drop\" title=\"Menu\" src=\"Styles/Icons/dropicon.png\" /> <!-- dropdown__img -->\n");
      out.write("                </div>\n");
      out.write("                <!-- FIN DIV MENU DESPLEGABLE  -->\n");
      out.write("                ");
 PersonaDAO pdao = new PersonaDAO();
      out.write("\n");
      out.write("                <!-- INICIO DIV NOMBRE DE USUARIO  -->\n");
      out.write("                <div class=\"top-div__username\">\n");
      out.write("                    ");
      out.print(pdao.obtenerNombrePersona(PERS_ID).replace("?", "Ñ"));
      out.write("\n");
      out.write("                </div>  \n");
      out.write("                <!-- FIN DIV NOMBRE DE USUARIO  -->\n");
      out.write("                <!-- INICIO DIV ICONO DE USUARIO  -->  \n");
      out.write("                <div class=\"top-div__iconuser\">\n");
      out.write("                    <span class=\"top-div__span top-div__span--iconuser\">");
      out.print(pdao.obtenerNombrePersona(PERS_ID).charAt(0));
      out.write("</span>\n");
      out.write("                </div>\n");
      out.write("                <!-- FIN DIV ICONO DE USUARIO  -->\n");
      out.write("            </div>\n");
      out.write("            <!-- FIN DIV TOPBAR -->    \n");
      out.write("            <!-- INICIO DIV BARRA LATERAL DERECHA--> \n");
      out.write("            <div class=\"left-div\">\n");
      out.write("                <!-- INICIO TITULO ASABER--> \n");
      out.write("                <div class=\"left-div__title\">\n");
      out.write("                    <img  title=\"Asaber | Plataforma Educativa\" class=\"left-div__logo\" src=\"Images/logo_text.png\" alt=\"alt\"/>          \n");
      out.write("                </div>\n");
      out.write("                <!-- FIN TITULO ASABER--> \n");
      out.write("\n");
      out.write("                <!-- INICIO TITULO MENU--> \n");
      out.write("                <div class=\"left-div__title--menu\" >Menu</div>\n");
      out.write("                <!-- FIN TITULO MENU-->\n");
      out.write("                <!-- INICIO DIV  MENU LATERAL -->\n");
      out.write("                <div class=\"left-menu\">\n");
      out.write("                    <ul  class=\"left-menu__ul\">\n");
      out.write("                        ");

                            AlumnoDAO adao = new AlumnoDAO();
                            DocenteDAO ddao = new DocenteDAO();
                            if (adao.verificarAlumno(PERS_ID)) {
                        
      out.write("\n");
      out.write("\n");
      out.write("                        <li id =\"li_home\" class=\"selected left-menu__li\" onclick=\"cargarInicio(this.id)\" >\n");
      out.write("                            <img  class=\"left-menu__icon\" src=\"Styles/Icons/home.png\" alt=\"alt\"/> \n");
      out.write("                            <span class=\"left-menu__text\"> Inicio</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li id=\"li_mod\" class=\"left-menu__li\" onclick=\"cargarPagModulo(this.id)\">\n");
      out.write("                            <img class=\"left-menu__icon\" src=\"Styles/Icons/module.png\" alt=\"alt\"/>\n");
      out.write("                            &nbsp;&nbsp; <span class=\"left-menu__text\">Modulos </span>\n");
      out.write("                        </li>      \n");
      out.write("\n");
      out.write("                        ");
 } else if (ddao.verificarDocente(PERS_ID)) { 
      out.write("\n");
      out.write("                        <li id =\"li_home\" class=\"selected left-menu__li\" onclick=\"cargarInicio(this.id)\">\n");
      out.write("                            <img  class=\"left-menu__icon\" src=\"Styles/Icons/home.png\" alt=\"alt\"/> \n");
      out.write("                            <span class=\"left-menu__text\">Inicio</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li id=\"li_mod\" class=\"left-menu__li\" onclick=\"cargarPagModulo(this.id)\">\n");
      out.write("                            <img  class=\"left-menu__icon\" src=\"Styles/Icons/module.png\" alt=\"alt\"/> \n");
      out.write("                            <span class=\"left-menu__text\">Modulos</span>\n");
      out.write("                        </li> \n");
      out.write("                        <li id=\"li_res\" class=\"left-menu__li\" onclick=\"verResultados(this.id)\">\n");
      out.write("                            <img class=\"left-menu__icon\"  src=\"Styles/Icons/result.png\" alt=\"alt\"/>\n");
      out.write("                            <span class=\"left-menu__text\">Resultados</span>\n");
      out.write("                        </li>\n");
      out.write("                        ");
 } else {  
      out.write("\n");
      out.write("                        <li id =\"li_home\" class=\"selected left-menu__li\" onclick=\"cargarInicio(this.id)\">\n");
      out.write("                            <img class=\"left-menu__icon\" src=\"Styles/Icons/home.png\" alt=\"alt\"/> \n");
      out.write("                            <span class=\"left-menu__text\">Inicio</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li id=\"li_mod\" class=\"left-menu__li\" onclick=\"cargarPagModulo(this.id)\">\n");
      out.write("                            <img  class=\"left-menu__icon\" src=\"Styles/Icons/module.png\" alt=\"alt\"/> \n");
      out.write("                            <span class=\"left-menu__text\">Modulos</span>\n");
      out.write("                        </li> \n");
      out.write("                        <li id=\"li_res\" class=\"left-menu__li\" onclick=\"verResultados(this.id)\">\n");
      out.write("                            <img class=\"left-menu__icon\" src=\"Styles/Icons/result.png\" alt=\"alt\"/>\n");
      out.write("                            <span class=\"left-menu__text\">Resultados</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li id=\"li_bus\" class=\"left-menu__li\" onclick=\"cargarBusquedUsuarios(this.id)\">\n");
      out.write("                            <img class=\"left-menu__icon\" src=\"Styles/Icons/search.png\" alt=\"alt\"/>\n");
      out.write("                            <span class=\"left-menu__text\">Buscar Usuarios</span>\n");
      out.write("                        </li>\n");
      out.write("                        <li id=\"li_reg\" class=\"left-menu__li\" onclick=\"verMenuRegistro(this.id)\" >\n");
      out.write("                            <img class=\"left-menu__icon\" src=\"Styles/Icons/form.png\" alt=\"alt\"/>\n");
      out.write("                            <span class=\"left-menu__text\">Añadir Usuarios</span>\n");
      out.write("                        </li>\n");
      out.write("                        <!-- INICIO SUB-MENU REGISTROS LATERAL -->\n");
      out.write("                        <ul class=\"left-menu__ul left-menu__ul--hidden\" >\n");
      out.write("                            <li id=\"alumno\" class=\"left-menu__li left-menu__li--hidden\" onclick=\"cargarForms(this.id)\"> \n");
      out.write("                                <img class=\"left-menu__icon\"src=\"Styles/Icons/student.png\" alt=\"alt\"/>\n");
      out.write("                                <span class=\"left-menu__text\">Alumno</span>\n");
      out.write("                            </li>\n");
      out.write("                            <li id=\"docente\"class=\"left-menu__li left-menu__li--hidden\" onclick=\"cargarForms(this.id)\">\n");
      out.write("                                <img class=\"left-menu__icon\" src=\"Styles/Icons/teacher.png\" alt=\"alt\" />\n");
      out.write("                                <span class=\"left-menu__text\"> Docente</span>\n");
      out.write("                            </li>\n");
      out.write("                        </ul>     \n");
      out.write("                        <!-- FIN SUB-MENU REGISTROS LATERAL -->\n");
      out.write("                        ");
 } 
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("\n");
      out.write("                    <div class=\"left-div__footer\">\n");
      out.write("                        Asaber 2023 - Version 1.3 \n");
      out.write("                    </div>\n");
      out.write("                </div>\n");
      out.write("                <!-- FIN DIV  MENU LATERAL -->\n");
      out.write("            </div>\n");
      out.write("            <!-- FIN DIV BARRA LATERAL DERECHA--> \n");
      out.write("        </div>\n");
      out.write("    </body>  \n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("  /* window.onbeforeunload = function (event)\n");
      out.write("    {\n");
      out.write("        return confirm(\"Confirm refresh\");\n");
      out.write("    }; */\n");
      out.write("\n");
      out.write("\n");
      out.write("    const pruebaMetodo = (modulo) => {\n");
      out.write("        $.post(\"/PersonaControlador/pruebaMetodo\", {modulo: modulo}, function (data) {\n");
      out.write("            window.location.replace(\"InicioSesion.jsp\");\n");
      out.write("            alertSucsses(\"Sesion cerrada correctamente\");\n");
      out.write("        });\n");
      out.write("    };\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
 //if(!indao.primerInicioSesion(PERS_ID)){ 
      out.write("\n");
      out.write("\n");
      out.write("<!--  <div class=\"modal_fondo passChange\" style=\"display: flex; \">\n");
      out.write("      <div class=\"div_modal\" style=\"display: flex; width: 460px; height: 170px;\">\n");
      out.write("          \n");
      out.write("          <div style=\"font-size: 22px; color: #744FA3;\"><b>CAMBIAR CONTRASEÑA</b></div>\n");
      out.write("          <br>\n");
      out.write("          <br>\n");
      out.write("          <div>\n");
      out.write("              <input type=\"password\" id=\"pass\" name=\"pass\" placeholder=\"Contraseña\"/>\n");
      out.write("              <br>\n");
      out.write("              <br>\n");
      out.write("              <input type=\"password\" id=\"pass_confirm\" name=\"pass-confirm\" placeholder=\"Confirmar Contraseña\"/>\n");
      out.write("              <br>\n");
      out.write("              <br>\n");
      out.write("              <button type=\"button\" style=\"float: right;\" onclick=\"cambiarPass('");
      out.print(PERS_ID);
      out.write("',$('#pass').val(),$('#pass_confirm').val())\" class=\"wAccept_bttn\">Guardar</button>\n");
      out.write("          </div>\n");
      out.write("      </div>\n");
      out.write("\n");
      out.write("  </div> ->>\n");
      out.write("\n");
 //} 
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
 }
      out.write('\n');
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
