/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-04-12 16:07:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Registros;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class mainPageRegistros_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"body-page\" >\n");
      out.write("    <div class=\"bar-buttons\">\n");
      out.write("        REGISTROS\n");
      out.write("        <div class=\"div-bttn\">\n");
      out.write("            <button onclick=\"addPerson()\" class=\"new-button bttn-añadir\"><img src=\"Icons/user-plus-solid.svg \" style=\"width: 20px; height: 20px; margin-right: 8px; margin-top: -4px; vertical-align: middle\" >Nuevo Registro <!-- --></button>\n");
      out.write("            <button onclick=\"searchPerson()\" class=\"new-button bttn-buscar\"><img src=\"Icons/search.svg\" style=\"width: 15px; height: 15px; margin-right:  8px; margin-top: -4px; vertical-align: middle\" >Buscar <!-- --></button>\n");
      out.write("        </div>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"add-person\">\n");
      out.write("\n");
      out.write("        Seleccione el tipo de persona que desea registrar.\n");
      out.write("\n");
      out.write("        <br>\n");
      out.write("        <fieldset>\n");
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <tr>\n");
      out.write("                    <th> <select id=\"select-person\" onchange=\"selectedStudent(this.value)\" >\n");
      out.write("                            <option>Seleccione...</option>\n");
      out.write("                            <option value=\"1\">Estudiante</option>\n");
      out.write("                            <option value=\"2\">Funcionario</option>\n");
      out.write("                        </select></th>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("            <table id=\"studenteDataSelected\" hidden>\n");
      out.write("                <tr>\n");
      out.write("\n");
      out.write("                    <th> <select id=\"Curso\" >\n");
      out.write("                            <option>CURSO</option>\n");
      out.write("                            <option value=\"1\">9</option>\n");
      out.write("                            <option value=\"2\">8</option>\n");
      out.write("                        </select>\n");
      out.write("                    </th>\n");
      out.write("                </tr>\n");
      out.write("                <tr>\n");
      out.write("\n");
      out.write("                    <th>  <select id=\"Jornada\" >\n");
      out.write("                            <option>JORNADA</option>\n");
      out.write("                            <option value=\"1\">Duirno</option>\n");
      out.write("                            <option value=\"2\">Tarde</option>\n");
      out.write("                        </select></th>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("            <table id=\"funcDataSelected\" hidden>\n");
      out.write("\n");
      out.write("                <tr>\n");
      out.write("\n");
      out.write("                    <th> <select id=\"tipoFuncionario\" >\n");
      out.write("                            <option>Tipo Funcionario...</option>\n");
      out.write("                            <option value=\"1\">Docente</option>\n");
      out.write("                            <option value=\"4\">Rector(a)</option>\n");
      out.write("                            <option value=\"2\">Secretaria(o)</option>\n");
      out.write("                            <option value=\"3\">Otro</option>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </select>\n");
      out.write("                    </th>\n");
      out.write("                </tr>\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("            <div style=\"margin-bottom:  15px;\"></div>\n");
      out.write("\n");
      out.write("            <button onclick=\"loadForm()\" class=\"btt-acept-add\">Aceptar</button>\n");
      out.write("        </fieldset>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"search-person\">\n");
      out.write("        <br>\n");
      out.write("        <table>\n");
      out.write("            <tr><td>Tipo&nbsp;</td><td><select  onchange=\"cursoSearchStudent(this.value)\">\n");
      out.write("                        <option value=\"00\">Seleccionar...</option>\n");
      out.write("                        <option value=\"0\">Estudiante</option>\n");
      out.write("                        <option value=\"1\">Docente</option>\n");
      out.write("                        <option value=\"2\">Funcionario</option>\n");
      out.write("\n");
      out.write("                    </select>&nbsp;&nbsp;</td></tr>\n");
      out.write("            <tr id=\"cursoSs\" hidden><td>Curso</td><td><select name=\"\" id=\"\"></select></td></tr>\n");
      out.write("            <tr><td> Nombre&nbsp;</td><td><input type=\"text\">&nbsp;&nbsp;</td></tr>\n");
      out.write("\n");
      out.write("            <tr><td> Num Documento&nbsp;</td><td><input type=\"text\">&nbsp;&nbsp;</td></tr>\n");
      out.write("            <tr></tr>\n");
      out.write("            <tr></tr>\n");
      out.write("            <tr></td><td><td> <button onclick=\"cargarDatosBusqueda()\" style=\"background-color: #009bff; float: right\" >Buscar</button></td></tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("        </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <br>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"load-form\">\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
