/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-04-12 16:07:59 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Registros;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import DAO.TipoArchivoDAO;
import DAO.CiudadDAO;
import DAO.TipoDocumentoDAO;
import Model.VO.DepartamentoVO;
import java.util.ArrayList;
import DAO.DepartamentoDAO;
import VO.TipoArchivoVO;
import VO.TipoDocumentoVO;
import VO.CiudadVO;

public final class registroEstudiantes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.TipoArchivoDAO");
    _jspx_imports_classes.add("DAO.DepartamentoDAO");
    _jspx_imports_classes.add("VO.TipoDocumentoVO");
    _jspx_imports_classes.add("VO.CiudadVO");
    _jspx_imports_classes.add("DAO.CiudadDAO");
    _jspx_imports_classes.add("DAO.TipoDocumentoDAO");
    _jspx_imports_classes.add("VO.TipoArchivoVO");
    _jspx_imports_classes.add("Model.VO.DepartamentoVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script src=\"Js/jquery.form.js\"></script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("    $(document).ready(function() {\n");
      out.write("        $(\"#datosPadre :input\").attr(\"disabled\", true);\n");
      out.write("        $(\"#datosMadre :input\").attr(\"disabled\", true);\n");
      out.write("        $(\"#datosAcu :input\").attr(\"disabled\", true);\n");
      out.write("    });\n");
      out.write("\n");
      out.write("\n");
      out.write("    $(function() {\n");
      out.write("        var fecha = new Date();\n");
      out.write("        $(\"#datepicker\").datepicker({\n");
      out.write("\n");
      out.write("            dateFormat: 'yy-mm-dd',\n");
      out.write("            changeMonth: true,\n");
      out.write("            changeYear: true,\n");
      out.write("            yearRange: \"1950:\" + fecha.getFullYear()\n");
      out.write("        });\n");
      out.write("        $(\"#datepicker1\").datepicker({\n");
      out.write("\n");
      out.write("            dateFormat: 'yy-mm-dd',\n");
      out.write("            changeMonth: true,\n");
      out.write("            changeYear: true,\n");
      out.write("            yearRange: \"1950:\" + fecha.getFullYear()\n");
      out.write("        });\n");
      out.write("        $(\"#datepicker2\").datepicker({\n");
      out.write("\n");
      out.write("            dateFormat: 'yy-mm-dd',\n");
      out.write("            changeMonth: true,\n");
      out.write("            changeYear: true,\n");
      out.write("            yearRange: \"1950:\" + fecha.getFullYear()\n");
      out.write("        });\n");
      out.write("        $(\"#datepicker3\").datepicker({\n");
      out.write("\n");
      out.write("            dateFormat: 'yy-mm-dd',\n");
      out.write("            changeMonth: true,\n");
      out.write("            changeYear: true,\n");
      out.write("            yearRange: \"1950:\" + fecha.getFullYear()\n");
      out.write("        });\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    var fecha = new Date();\n");
      out.write("    $('#anoCursado').datepicker({\n");
      out.write("\n");
      out.write("        changeMonth: false,\n");
      out.write("        changeYear: true,\n");
      out.write("        dateFormat: 'yy',\n");
      out.write("        showButtonPanel: true,\n");
      out.write("        closeText: \"Aceptar\",\n");
      out.write("        yearRange: \"1950:\" + fecha.getFullYear(),\n");
      out.write("\n");
      out.write("        onClose: function() {\n");
      out.write("\n");
      out.write("            var iYear = $(\"#ui-datepicker-div .ui-datepicker-year :selected\").val();\n");
      out.write("            $(this).datepicker('setDate', new Date(iYear, 1));\n");
      out.write("        },\n");
      out.write("\n");
      out.write("        beforeShow: function() {\n");
      out.write("            $(this).datepicker(\"widget\").addClass('hide-calendar');\n");
      out.write("            if ((selDate = $(this).val()).length > 0) {\n");
      out.write("                iYear = selDate.substring(selDate.length - 4, selDate.length);\n");
      out.write("                $(this).datepicker('option', 'defaultDate', new Date(iYear, 1));\n");
      out.write("                $(this).datepicker('setDate', new Date(iYear, 1));\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    });\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"form-student\">\n");
      out.write("    <div class=\"datos-no-aca\">\n");
      out.write("\n");
      out.write("        <form action=\"ServletMainController\" method=\"post\" id=\"formularioEstudiante\" >\n");
      out.write("\n");
      out.write("            <div class=\"datos-principales\">\n");
      out.write("\n");
      out.write("                <fieldset>\n");
      out.write("                    <legend>ESTUDIANTE - Datos Personales</legend>\n");
      out.write("\n");
      out.write("                    <input type=\"text\" name=\"modulo\" value=\"registroEstudiante\" hidden>\n");
      out.write("\n");
      out.write("                    <table class=\"tbl-form-student\" >\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>Primer nombre <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Segundo nombre</th>\n");
      out.write("                                <th>Primer apellido <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Segundo apellido <span class=\"required-symbo\">*</span></th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <td><input type=\"text\" name=\"pNombreEstudiante\" required></td>\n");
      out.write("                                <td><input type=\"text\" name=\"sNombreEstudiante\"></td>\n");
      out.write("                                <td><input type=\"text\" name=\"pApellidoEstudiante\"required></td>\n");
      out.write("                                <td><input type=\"text\" name=\"sApellidoEstudiante\"required></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("                    <br>\n");
      out.write("                    <table>\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>Tipo de documento <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Numero de documento <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Fecha de nacimiento <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Genero <span class=\"required-symbo\">*</span></th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <td><select name=\"tipoDocumentoEstudiante\"  required>\n");
      out.write("                                        <option></option>\n");
      out.write("                                        ");
 TipoDocumentoDAO tipoDocumentoDAO = new TipoDocumentoDAO();
                                            ArrayList<TipoDocumentoVO> tidoVo = tipoDocumentoDAO.obtenerTipoDocumento();
                                            for (TipoDocumentoVO datosTido : tidoVo) {
                                        
      out.write("\n");
      out.write("                                        <option value=\"");
      out.print(datosTido.getTIDO_ID());
      out.write('"');
      out.write('>');
      out.print(datosTido.getTIDO_NOMBRE());
      out.write("</option>\n");
      out.write("                                        ");


                                            }

                                        
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                    </select></td>\n");
      out.write("                                <td><input type=\"number\" name=\"numDocumentoEstudiante\"  required></td>\n");
      out.write("                                <td><input type=\"text\" id=\"datepicker\" name=\"fechaNacimientoEstudiante\" required=\"true\" readonly=\"readonly\"></td>\n");
      out.write("                                <td><select name=\"generoEstudiante\" id=\"\" required>\n");
      out.write("                                        <option></option>\n");
      out.write("                                        <option>MASCULINO</option>\n");
      out.write("                                        <option>FEMENINO</option>\n");
      out.write("                                    </select></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("                    <br>\n");
      out.write("                    <table id=\"dep\">\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>Dep de nacimiento <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Ciudad de nacimiento <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Direccion <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Estrato <span class=\"required-symbo\">*</span></th>\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <td><select id=\"depNacimientoEstudiante\" name=\"depNacimientoEstudiante\" onchange=\"cargarCiudadesXDep(this.value, this.id)\" required >\n");
      out.write("                                        <option></option>\n");
      out.write("                                        ");
 DepartamentoDAO dep = new DepartamentoDAO();
                                            ArrayList<DepartamentoVO> deps = dep.obtenerDepartamentos();
                                            System.out.println(deps.size());
                                            for (DepartamentoVO datos : deps) {
                                        
      out.write("\n");
      out.write("                                        <option value=\"");
      out.print(datos.getDEPA_ID());
      out.write('"');
      out.write('>');
      out.print(datos.getDEPA_NOMBRE());
      out.write("</option>\n");
      out.write("                                        ");

                                            }
                                        
      out.write("\n");
      out.write("                                    </select></td>\n");
      out.write("                                <td><select name=\"ciuNacimientoEstudiante\" id=\"ciuds\" required>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                    </select></td>\n");
      out.write("                                <td><input type=\"text\" name=\"dirEstudiante\" required></td>\n");
      out.write("                                <td><select name=\"estratoEstudiante\" id=\"\" required>\n");
      out.write("                                        <option>1</option>\n");
      out.write("                                        <option>2</option>\n");
      out.write("                                        <option>3</option>\n");
      out.write("                                        <option>4</option>\n");
      out.write("                                        <option>5</option>\n");
      out.write("                                        <option>6</option>\n");
      out.write("                                    </select></td>\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("                    <br>\n");
      out.write("                    <table>\n");
      out.write("                        <thead>\n");
      out.write("                            <tr>\n");
      out.write("                                <th>Eps <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Barrio <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Ciudad de residencia <span class=\"required-symbo\">*</span></th>\n");
      out.write("                                <th>Numero telefonico <span class=\"required-symbo\">*</span></th>\n");
      out.write("\n");
      out.write("                            </tr>\n");
      out.write("                        </thead>\n");
      out.write("                        <tbody>\n");
      out.write("                            <tr>\n");
      out.write("                                <td><input type=\"text\" name=\"epsEstudiante\" required></td>\n");
      out.write("                                <td><input type=\"text\" name=\"barrioEstudiante\" required></td>\n");
      out.write("                                <td><select name=\"ciuResidenciaEstudiante\"  required>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                        ");
 CiudadDAO ciudadDAO = new CiudadDAO();
                                            ArrayList<CiudadVO> ciudadVO = ciudadDAO.obtenerCiudadesTodas();
                                            for (CiudadVO dato : ciudadVO) {
                                        
      out.write("\n");
      out.write("                                        <\n");
      out.write("                                        <option value=\"");
      out.print(dato.getCIUD_ID());
      out.write('"');
      out.write('>');
      out.print(dato.getCIUD_NOMBRE());
      out.write("</option>\n");
      out.write("                                        ");


                                            }


                                        
      out.write("\n");
      out.write("\n");
      out.write("                                    </select>\n");
      out.write("\n");
      out.write("                                </td>\n");
      out.write("                                <td><input type=\"number\" name=\"telEstudiante\" ></td>\n");
      out.write("\n");
      out.write("                            </tr>\n");
      out.write("                        </tbody>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("                </fieldset>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("            <br>\n");
      out.write("            <br>\n");
      out.write("\n");
      out.write("            <div class=\"datos-familiares\">\n");
      out.write("                <input id=\"verf-padre\" value=\"0\" hidden/>\n");
      out.write("                <input id=\"verf-madre\" value=\"0\" hidden/>\n");
      out.write("                <input id=\"verf-acu\" value=\"0\" hidden/>\n");
      out.write("                <fieldset>\n");
      out.write("                    <legend>Datos Familiares</legend>\n");
      out.write("                    <table>\n");
      out.write("                        <tr>\n");
      out.write("                            <th onclick=\"validarDatos('datosPadre')\" style=\"cursor: pointer; font-size: 16px; background-color: #2c7eea; padding: 10px; color: white; border-radius: 2px;\"> Datos del padre\n");
      out.write("                                <label id=\"lblP\" style=\" float: right; background: #FFF; border-radius: 3px; color: #2B2B2C; padding: 6px; font-size: 14px; cursor: pointer; \">ABRIR\n");
      out.write("                                    <img src=\"Icons/arrow-circle-down-solid.svg\" style=\" float: right; width: 20px; height: 20px; margin-left: 10px;  vertical-align: middle\"></label></th>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                    <br>\n");
      out.write("                    <table>\n");
      out.write("                        <tr>\n");
      out.write("                            <th><img src=\"Icons/info-circle.svg\" style=\"height:  30px; margin-right: 10px;  margin-left: 5px; margin-bottom: 3px; vertical-align: middle\" >\n");
      out.write("                                En caso de no conocer los datos del padre o que el ya no viva favor abrir esta pestaña, gracias.</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <br>\n");
      out.write("                    <div  id=\"datosPadre\" hidden=\"\">\n");
      out.write("\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Primer nombre</th>\n");
      out.write("                                    <th>Segundo nombre</th>\n");
      out.write("                                    <th>Primer apellido</th>\n");
      out.write("                                    <th>Segundo apellido</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><input type=\"text\" name=\"pNombrePadre\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"sNombrePadre\"></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"pApellidoPadre\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"sApellidoPadre\" required></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Tipo de documento</th>\n");
      out.write("                                    <th>Numero de documento</th>\n");
      out.write("                                    <th>Fecha de nacimiento</th>\n");
      out.write("                                    <th>Dep de nacimiento</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><select name=\"tipoDocumentoPadre\" id=\"\" required>\n");
      out.write("                                            ");
 TipoDocumentoDAO tipoDocumentoDAOPadre = new TipoDocumentoDAO();
                                                ArrayList<TipoDocumentoVO> tidoVoPadre = tipoDocumentoDAOPadre.obtenerTipoDocumento();
                                                for (TipoDocumentoVO datosTido : tidoVoPadre) {
                                            
      out.write("\n");
      out.write("                                            <option value=\"");
      out.print(datosTido.getTIDO_ID());
      out.write('"');
      out.write('>');
      out.print(datosTido.getTIDO_NOMBRE());
      out.write("</option>\n");
      out.write("                                            ");


                                                }

                                            
      out.write("\n");
      out.write("\n");
      out.write("                                        </select></td>\n");
      out.write("                                    <td><input type=\"number\" name=\"numDocumentoPadre\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"fecNacimientoPadre\" id=\"datepicker2\"  readonly=\"readonly\" required></td>\n");
      out.write("                                    <td><select id=\"depNacimientoPadre\" name=\"depNacimientoPadre\" onchange=\"cargarCiudadesXDep(this.value, this.id)\" required>\n");
      out.write("\n");
      out.write("                                            ");
 DepartamentoDAO depPadre = new DepartamentoDAO();
                                                ArrayList<DepartamentoVO> depsPadre = depPadre.obtenerDepartamentos();

                                                for (DepartamentoVO datos : depsPadre) {
                                            
      out.write("\n");
      out.write("                                            <option value=\"");
      out.print(datos.getDEPA_ID());
      out.write('"');
      out.write('>');
      out.print(datos.getDEPA_NOMBRE());
      out.write("</option>\n");
      out.write("                                            ");

                                                }
                                            
      out.write("\n");
      out.write("\n");
      out.write("                                        </select></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Ciudad de nacimiento</th>\n");
      out.write("                                    <th>Direccion</th>\n");
      out.write("                                    <th>Estrato</th>\n");
      out.write("                                    <th>Barrio</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><select name=\"ciuNacimientoPadre\" id=\"ciudPadre\" required></select></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"dirPadre\" required></th>\n");
      out.write("                                    <td><select name=\"estratoPadre\" required>\n");
      out.write("                                            <option>1</option>\n");
      out.write("                                            <option>2</option>\n");
      out.write("                                            <option>3</option>\n");
      out.write("                                            <option>4</option>\n");
      out.write("                                            <option>5</option>\n");
      out.write("                                            <option>6</option>\n");
      out.write("                                        </select></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"barrioPadre\" required></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("                        <table style=\"width: 75%;\">\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("\n");
      out.write("                                    <th>Ciudad de residencia</th>\n");
      out.write("                                    <th>Numero telefonico</th>\n");
      out.write("                                    <th >Ocupación</th>\n");
      out.write("                                    <th></th>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><select  name=\"ciuResidenciaPadre\" required>\n");
      out.write("                                            ");
 CiudadDAO ciudadDAOPadre = new CiudadDAO();
                                                ArrayList<CiudadVO> ciudadVOPadre = ciudadDAOPadre.obtenerCiudadesTodas();
                                                for (CiudadVO dato : ciudadVOPadre) {
                                            
      out.write("\n");
      out.write("                                            <\n");
      out.write("                                            <option value=\"");
      out.print(dato.getCIUD_ID());
      out.write('"');
      out.write('>');
      out.print(dato.getCIUD_NOMBRE());
      out.write("</option>\n");
      out.write("                                            ");


                                                }


                                            
      out.write("\n");
      out.write("                                        </select>\n");
      out.write("                                    </td>\n");
      out.write("                                    <td><input type=\"number\" name=\"telPadre\" required></td>\n");
      out.write("                                    <td colspan=\"2\"><input type=\"text\" name=\"ocupacionPadre\" required></td>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("                        <br>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <table>\n");
      out.write("                        <tr>\n");
      out.write("                            <th onclick=\"validarDatos('datosMadre')\" style=\"cursor: pointer; font-size: 16px; background-color: #2c7eea; padding: 10px; color: white; border-radius: 2px;\">Datos de la Madre\n");
      out.write("                                <label  id=\"lblM\" style=\" float: right; background: #FFF; border-radius: 3px; color: #2B2B2C; padding: 6px; font-size: 14px; cursor: pointer; \">ABRIR\n");
      out.write("                                    <img src=\"Icons/arrow-circle-down-solid.svg\" style=\" float: right; width: 20px; height: 20px; margin-left: 10px;  vertical-align: middle\"></label></th>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                    <br>\n");
      out.write("                    <table>\n");
      out.write("                        <tr>\n");
      out.write("                            <th><img src=\"Icons/info-circle.svg\" style=\"height:  30px; margin-right: 10px;  margin-left: 5px; margin-bottom: 3px; vertical-align: middle\" >\n");
      out.write("                                En caso de no conocer los datos de la madre o que ella ya no viva favor no abrir esta pestaña, gracias.</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                    <br>\n");
      out.write("                    <div id=\"datosMadre\" hidden=\"\">\n");
      out.write("                        <br>\n");
      out.write("                        <br>\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Primer nombre</th>\n");
      out.write("                                    <th>Segundo nombre</th>\n");
      out.write("                                    <th>Primer apellido</th>\n");
      out.write("                                    <th>Segundo apellido</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><input type=\"text\" name=\"pNombreMadre\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"sNombreMadre\"  ></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"pApellidoMadre\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"sApellidoMadre\" required></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Tipo de documento</th>\n");
      out.write("                                    <th>Numero de documento</th>\n");
      out.write("                                    <th>Fecha de nacimiento</th>\n");
      out.write("                                    <th>Dep de nacimiento</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><select name=\"tipoDocumentoMadre\" id=\"\">\n");
      out.write("\n");
      out.write("                                            ");
 TipoDocumentoDAO tipoDocumentoDAOMadre = new TipoDocumentoDAO();
                                                ArrayList<TipoDocumentoVO> tidoVoMadre = tipoDocumentoDAOMadre.obtenerTipoDocumento();
                                                for (TipoDocumentoVO datosTido : tidoVoMadre) {
                                            
      out.write("\n");
      out.write("                                            <option value=\"");
      out.print(datosTido.getTIDO_ID());
      out.write('"');
      out.write('>');
      out.print(datosTido.getTIDO_NOMBRE());
      out.write("</option>\n");
      out.write("                                            ");


                                                }

                                            
      out.write("\n");
      out.write("\n");
      out.write("                                        </select></td>\n");
      out.write("                                    <td><input type=\"number\" name=\"numDocumentoMadre\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"fecNacimientoMadre\" id=\"datepicker1\" readonly=\"readonly\" required></td>\n");
      out.write("                                    <td><select id=\"depNacimientoMadre\" name=\"depNacimientoMadre\" onchange=\"cargarCiudadesXDep(this.value, this.id)\" required>\n");
      out.write("\n");
      out.write("                                            ");
 DepartamentoDAO depMadre = new DepartamentoDAO();
                                                ArrayList<DepartamentoVO> depsMadre = depMadre.obtenerDepartamentos();

                                                for (DepartamentoVO datos : depsMadre) {
                                            
      out.write("\n");
      out.write("                                            <option value=\"");
      out.print(datos.getDEPA_ID());
      out.write('"');
      out.write('>');
      out.print(datos.getDEPA_NOMBRE());
      out.write("</option>\n");
      out.write("                                            ");

                                                }
                                            
      out.write("\n");
      out.write("\n");
      out.write("                                        </select></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Ciudad de nacimiento</th>\n");
      out.write("                                    <th>Direccion</th>\n");
      out.write("                                    <th>Estrato</th>\n");
      out.write("                                    <th>Barrio</th>\n");
      out.write("                                </tr>\n");
      out.write("\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><select name=\"ciuNacimientoMadre\" id=\"ciudMadre\" required></select></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"dirMadre\" required></td>\n");
      out.write("                                    <td><select name=\"estratoMadre\" required>\n");
      out.write("                                            <option>1</option>\n");
      out.write("                                            <option>2</option>\n");
      out.write("                                            <option>3</option>\n");
      out.write("                                            <option>4</option>\n");
      out.write("                                            <option>5</option>\n");
      out.write("                                            <option>6</option>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                        </select></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"barrioMadre\" required></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("                        <table style=\"width: 75%;\">\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("\n");
      out.write("                                    <th>Ciudad de residencia</th>\n");
      out.write("                                    <th>Numero telefonico</th>\n");
      out.write("                                    <th>Ocupación</th>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>\n");
      out.write("                                        <select  name=\"ciuResidenciaMadre\" required>\n");
      out.write("                                            ");
 CiudadDAO ciudadDAOMadre = new CiudadDAO();
                                                ArrayList<CiudadVO> ciudadVOMadre = ciudadDAOMadre.obtenerCiudadesTodas();
                                                for (CiudadVO dato : ciudadVOMadre) {
                                            
      out.write("\n");
      out.write("                                            <\n");
      out.write("                                            <option value=\"");
      out.print(dato.getCIUD_ID());
      out.write('"');
      out.write('>');
      out.print(dato.getCIUD_NOMBRE());
      out.write("</option>\n");
      out.write("                                            ");


                                                }


                                            
      out.write("\n");
      out.write("                                        </select></td>\n");
      out.write("                                    <td><input type=\"number\" name=\"telMadre\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"ocupacionMadre\" required></td>\n");
      out.write("                                    <td></td>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("                        <br>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("                    <table>\n");
      out.write("                        <tr>\n");
      out.write("                            <th onclick=\"validarDatos('datosAcu')\"  style=\"  cursor: pointer; font-size: 16px; background-color: #2c7eea; padding: 10px; color: white; border-radius: 2px;\">Datos del Acudiente\n");
      out.write("                                <label id=\"lblAcu\" style=\" float: right; background: #FFF; border-radius: 3px; color: #2B2B2C; padding: 6px; font-size: 14px; cursor: pointer; \">ABRIR\n");
      out.write("                                    <img src=\"Icons/arrow-circle-down-solid.svg\" style=\" float: right; width: 20px; height: 20px; margin-left: 10px;  vertical-align: middle\"></label></th>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                    <br>\n");
      out.write("                    <table>\n");
      out.write("                        <tr>\n");
      out.write("                            <th><img src=\"Icons/info-circle.svg\" style=\" height: 30px; margin-right: 10px; font-size: 16px; margin-left: 5px; margin-bottom: 3px; vertical-align: middle\" >\n");
      out.write("                                En caso de no tener acudiente aparte del padre o la madre favor no abrir esta pestaña, gracias.</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </table>\n");
      out.write("                    <br>\n");
      out.write("                    <div id=\"datosAcu\" hidden=\"\">\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Primer nombre</th>\n");
      out.write("                                    <th>Segundo nombre</th>\n");
      out.write("                                    <th>Primer apellido</th>\n");
      out.write("                                    <th>Segundo apellido</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><input type=\"text\" name=\"pNombreAcu\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"sNombreAcu\" ></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"pApellidoAcu\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"sApellidoAcu\" required></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Tipo de documento</th>\n");
      out.write("                                    <th>Numero de documento</th>\n");
      out.write("                                    <th>Fecha de nacimiento</th>\n");
      out.write("                                    <th>Dep de nacimiento</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><select name=\"tipoDocumentoAcu\" id=\"\" required>\n");
      out.write("                                            ");
 TipoDocumentoDAO tipoDocumentoDAOAcu = new TipoDocumentoDAO();
                                                ArrayList<TipoDocumentoVO> tidoVoAcu = tipoDocumentoDAOAcu.obtenerTipoDocumento();
                                                for (TipoDocumentoVO datosTido : tidoVoAcu) {
                                            
      out.write("\n");
      out.write("                                            <option value=\"");
      out.print(datosTido.getTIDO_ID());
      out.write('"');
      out.write('>');
      out.print(datosTido.getTIDO_NOMBRE());
      out.write("</option>\n");
      out.write("                                            ");


                                                }

                                            
      out.write("\n");
      out.write("\n");
      out.write("                                        </select></td>\n");
      out.write("                                    <td><input type=\"number\" name=\"numDocumentoAcu\" required></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"fecNacimientoAcu\" id=\"datepicker3\"  readonly=\"readonly\" required></td>\n");
      out.write("                                    <td><select id=\"depNacimientoAcu\" name=\"depNacimientoAcu\" onchange=\"cargarCiudadesXDep(this.value, this.id)\" required>\n");
      out.write("\n");
      out.write("                                            ");
 DepartamentoDAO depAcudiente = new DepartamentoDAO();
                                                ArrayList<DepartamentoVO> depsAcudiente = depAcudiente.obtenerDepartamentos();

                                                for (DepartamentoVO datos : depsAcudiente) {
                                            
      out.write("\n");
      out.write("                                            <option value=\"");
      out.print(datos.getDEPA_ID());
      out.write('"');
      out.write('>');
      out.print(datos.getDEPA_NOMBRE());
      out.write("</option>\n");
      out.write("                                            ");

                                                }
                                            
      out.write("\n");
      out.write("\n");
      out.write("                                        </select></td>\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("                                    <th>Ciudad de nacimiento</th>\n");
      out.write("                                    <th>Direccion</th>\n");
      out.write("                                    <th>Estrato</th>\n");
      out.write("                                    <th>Barrio</th>\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><select name=\"ciuNacimientoAcu\" id=\"ciudAcu\" required></select></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"dirAcu\" required></td>\n");
      out.write("                                    <td><Select name=\"estratoAcu\" required>\n");
      out.write("                                            <option>1</option>\n");
      out.write("                                            <option>2</option>\n");
      out.write("                                            <option>3</option>\n");
      out.write("                                            <option>4</option>\n");
      out.write("                                            <option>5</option>\n");
      out.write("                                            <option>6</option>\n");
      out.write("\n");
      out.write("                                        </Select></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"barrioAcu\" required></td>\n");
      out.write("                                </tr>\n");
      out.write("                        </table>\n");
      out.write("                        <br>\n");
      out.write("                        <table>\n");
      out.write("                            <thead>\n");
      out.write("                                <tr>\n");
      out.write("\n");
      out.write("                                    <th>Ciudad de residencia</th>\n");
      out.write("                                    <th>Numero telefonico</th>\n");
      out.write("                                    <th>Parentesco</th>\n");
      out.write("                                    <th>Ocupación</th>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                            </thead>\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>\n");
      out.write("                                        <select  name=\"ciuResidenciaAcu\" required>\n");
      out.write("                                            ");
 CiudadDAO ciudadDAOAcu = new CiudadDAO();
                                                ArrayList<CiudadVO> ciudadVOAcu = ciudadDAOAcu.obtenerCiudadesTodas();
                                                for (CiudadVO dato : ciudadVOAcu) {
                                            
      out.write("\n");
      out.write("                                            <\n");
      out.write("                                            <option value=\"");
      out.print(dato.getCIUD_ID());
      out.write('"');
      out.write('>');
      out.print(dato.getCIUD_NOMBRE());
      out.write("</option>\n");
      out.write("                                            ");


                                                }


                                            
      out.write("\n");
      out.write("                                        </select>\n");
      out.write("\n");
      out.write("                                    </td>\n");
      out.write("                                    <td><input type=\"number\" name=\"telAcu\" required></td>\n");
      out.write("                                    <td><select name=\"parentescoAcu\" id=\"\" required>\n");
      out.write("                                            <option>ABUELO/ABUELA</option>\n");
      out.write("                                            <option>TIO/TIA</option>\n");
      out.write("                                            <option>HERMANO/HERMANA</option>\n");
      out.write("                                            <option>PRIMO/PRIMA</option>\n");
      out.write("                                            <option>SOBRINO/SOBRINA</option>\n");
      out.write("                                            <option>OTRO</option>\n");
      out.write("\n");
      out.write("                                        </select></td>\n");
      out.write("                                    <td><input type=\"text\" name=\"ocupacionAcu\" required></td>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                            </tbody>\n");
      out.write("                        </table>\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                </fieldset>\n");
      out.write("                <br>\n");
      out.write("                <button id=\"buttonForm\" class=\"bttn-save-form\" type=\"button\" onclick=\"openModalForm()\"  ><img src=\"Icons/arrow-alt-circle-right.svg\" style=\"width: 21px; height: 21px; margin-right: 15px; margin-top: -4px; vertical-align: middle\" >SIGUIENTE</button>\n");
      out.write("\n");
      out.write("                <br>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    <div class=\"datos-academicos\" hidden=\"\">\n");
      out.write("        <fieldset>\n");
      out.write("            <legend>Datos academicos</legend>\n");
      out.write("            <table>\n");
      out.write("                <tr><th>\n");
      out.write("                        Instituciones en las cuales se ha estado el estudiante\n");
      out.write("                    </th></tr>\n");
      out.write("            </table>\n");
      out.write("            <br>\n");
      out.write("            <table class=\"table-inst\" id=\"table-inst\" cellpadding=\"0\" cellspacing=\"0\">\n");
      out.write("                <thead>\n");
      out.write("                <th><label>Institucion</label></th>\n");
      out.write("                <th><label>Año</label></th>\n");
      out.write("                <th><label>Grado cursado</label></th>\n");
      out.write("                <th></th>\n");
      out.write("                </thead>\n");
      out.write("                <tbody><tr class=\"tr-options\"><td><input   id=\"nombreInst\" type=\"text\" placeholder=\"Nombre\"></td>\n");
      out.write("                        <td><input id=\"anoCursado\" type=\"text\" placeholder=\"Año\"></td>\n");
      out.write("                        <td>\n");
      out.write("                            <select id=\"cursoInst\">\n");
      out.write("                                <option value=\"\" disabled selected>SELECCIONE UN CURSO</option>\n");
      out.write("                                <option value=\"1\">Primero</option>\n");
      out.write("                                <option value=\"2\">Segundo</option>\n");
      out.write("                                <option value=\"3\">Tercero</option>\n");
      out.write("                                <option value=\"4\">Cuarto</option>\n");
      out.write("                                <option value=\"5\">Quinto</option>\n");
      out.write("                                <option value=\"6\">Sexto</option>\n");
      out.write("                                <option value=\"7\">Septimo</option>\n");
      out.write("                                <option value=\"8\">Octavo</option>\n");
      out.write("                                <option value=\"9\">Noveno</option>\n");
      out.write("                                <option value=\"10\">Decimo</option>\n");
      out.write("                                <option value=\"11\">Once</option>\n");
      out.write("\n");
      out.write("                            </select>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td style=\"align-content: center;\"><label onclick=\"agregarFilasTablaIns()\" style=\" cursor: pointer;border-radius: 3px; padding: 5px; background: #41d34b; color: #FFF; font-family: MonserratSemiBold; font-size: 14px; letter-spacing: 1px;\">\n");
      out.write("                                <img  src=\"Icons/layer-plus.svg\" style=\"width: 19px; height: 19px; margin-left:   3px;  margin-right: 15px; margin-top: 0px; vertical-align: middle; cursor:  pointer\"  >\n");
      out.write("                                AÑADIR\n");
      out.write("                            </label></td>\n");
      out.write("                    </tr></tbody>\n");
      out.write("            </table>\n");
      out.write("\n");
      out.write("        </fieldset>\n");
      out.write("\n");
      out.write("        <br>\n");
      out.write("        <br>\n");
      out.write("        <fieldset>\n");
      out.write("            <legend>Documentos personales</legend>\n");
      out.write("            <br>\n");
      out.write("            <form method=\"post\" action=\"ServletMainController\" enctype=\"multipart/form-data\"  id=\"documentoPersonal\">\n");
      out.write("\n");
      out.write("                <table CELLSPACING=\"0\" CELLPADDING=\"0\" class=\"table-documents\" id=\"table-documents\">\n");
      out.write("                    <thead>\n");
      out.write("                    <th><label for=\"\">Tipo de documento</label></th>\n");
      out.write("                    <th><label for=\"\">Archivo</label></th>\n");
      out.write("                    <th></th>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr class=\"tr-options-documetns\">\n");
      out.write("                            <td><select name=\"tipo-documento\" id=\"tipo-doc\"  >\n");
      out.write("                                    <option value=\"\" disabled selected>SELECCIONE UN DOCUMENTO</option>\n");
      out.write("                                    ");
 TipoArchivoDAO tipoArchivoDAO = new TipoArchivoDAO();
                                        ArrayList<TipoArchivoVO> tipoArchivoVO = tipoArchivoDAO.tiposArchivoEstudiante();
                                        for (TipoArchivoVO dato : tipoArchivoVO) {
                                    
      out.write("\n");
      out.write("                                    <option value=\"");
      out.print(dato.getTIAR_ID());
      out.write('"');
      out.write('>');
      out.print(dato.getTIAR_NOMBRE());
      out.write("</option>\n");
      out.write("                                    ");


                                        }

                                    
      out.write("\n");
      out.write("\n");
      out.write("                                </select></td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <input id=\"input-file\" class=\"input-file\" type=\"file\" name=\"input-file\" required />\n");
      out.write("                                <label id=\"label-doc\" class=\"blue-color-button\" for=\"input-file\"><img src=\"Icons/file-pdf.svg\" style=\"width: 17px; height: 17px; margin-right:  5px;  margin-top: -4px; vertical-align: middle\" >Cargar Archivo</label>\n");
      out.write("                                <input type=\"text\" name=\"modulo\" value=\"subirArchivo\" hidden>\n");
      out.write("                                <input  type=\"text\" name=\"tipo-documento\" id=\"tipo-documento\"hidden>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <button type=\"submit\" id=\"añadir\" class=\"green-color-button\" onclick=\"agregarFilasTablaDoc()\" ><img src=\"Icons/upload-solid.svg\" style=\"width: 20px; height: 20px; margin-right:  15px; margin-top: -4px; vertical-align: middle\" > SUBIR</button>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table> -->\n");
      out.write("\n");
      out.write("\n");
      out.write("                <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <button  type=\"button\" class=\"green-color-button\" onclick=\"registrarDatosAcademico();\" style=\"background-color: #2c7eea; padding: 15px; float: right;\" ><img src=\"Icons/save-solid.svg\" style=\"width: 20px; height: 20px; margin-right:  15px; margin-top: -4px; vertical-align: middle\" >FINALIZAR</button>\n");
      out.write("            </form>\n");
      out.write("        </fieldset>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("    $(\".input-file\").change(function() {\n");
      out.write("\n");
      out.write("\n");
      out.write("        var filename = $(this).val().split('\\\\').pop();\n");
      out.write("\n");
      out.write("        var extencion = filename.substring(filename.lastIndexOf(\".\"));\n");
      out.write("\n");
      out.write("        if (extencion === \".pdf\") {\n");
      out.write("\n");
      out.write("            var idname = $(this).attr('name');\n");
      out.write("            console.log($(this));\n");
      out.write("            console.log(filename);\n");
      out.write("            console.log(idname);\n");
      out.write("\n");
      out.write("            $(\"#label-doc\").html(\"<img src='Icons/file-pdf.svg' style='width: 17px; height: 17px; margin-right:  5px;  margin-top: -4px; vertical-align: middle'>\" + \"  \" + filename);\n");
      out.write("        } else {\n");
      out.write("            $(\".input-file\").val(\"\");\n");
      out.write("            alertError(\"El archivo debe ser formato <b>PDF</b>\");\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("\n");
      out.write("    $(\"#añadir\").click(function(e) {\n");
      out.write("        if ($(\".input-file\").val() !== \"\") {\n");
      out.write("            var archivo = $(\".input-file\").val();\n");
      out.write("\n");
      out.write("\n");
      out.write("            $('#documentoPersonal').ajaxForm({\n");
      out.write("\n");
      out.write("                success: function(msg) {\n");
      out.write("\n");
      out.write("                    alertSucsses(\"Achivo subido exitosamente.\")\n");
      out.write("                    var nombre_doc = \"deleteFile(\" + msg + \")\";\n");
      out.write("\n");
      out.write("                    var idDocTipo = $(\"#tipo-doc\").val();\n");
      out.write("\n");
      out.write("                    var combo = document.getElementById(\"tipo-doc\");\n");
      out.write("                    var selected = combo.options[combo.selectedIndex].innerText;\n");
      out.write("                    $(\"#tipo-doc option:selected\").remove();\n");
      out.write("\n");
      out.write("                    $('.table-documents > tbody').append('<tr><td>' + selected + '</td><td>' + $(\"#label-doc\").text() + '</td><td><button id=' + msg + ' class=borrar onclick=eliminarFilaDocumentos(' + idDocTipo + '),deleteRow(this),deleteFile(this.id)  style=background-color:#ff4c3d  ><img src=\"Icons/close.svg\" style=\"width: 17px; height: 17px; margin-right:  5px; margin-top: -4px; vertical-align: middle\" > Eliminar</button></td></tr>');\n");
      out.write("                    $(\"#label-doc\").show();\n");
      out.write("                    $(\"#label-doc\").html(\" \");\n");
      out.write("                    $(\"#label-doc\").append(\"<img src='Icons/file-pdf.svg' style='width: 17px; height: 17px; margin-right:  5px;  margin-top: -4px; vertical-align: middle'>  Cargar Archivo\");\n");
      out.write("                    $(\".input-file\").val(\"\");\n");
      out.write("                    $(\".borrar\").addClass(\"red-color-button\");\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                },\n");
      out.write("                error: function(msg) {\n");
      out.write("                    alertError(\"Se produjo un error al subir el archivo.\");\n");
      out.write("                }\n");
      out.write("            });\n");
      out.write("\n");
      out.write("\n");
      out.write("        } else {\n");
      out.write("\n");
      out.write("            alertError(\"Porfavor cargue un archivo.\");\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("\n");
      out.write("    /*    $(function() {\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("     $('#documentoPersonal').ajaxForm({\n");
      out.write("\n");
      out.write("     success: function(msg) {\n");
      out.write("\n");
      out.write("\n");
      out.write("     if ($(\".input-file\").val() !== \"\") {\n");
      out.write("     var nombre_doc = \"deleteFile(\" + msg + \")\";\n");
      out.write("     alert(nombre_doc);\n");
      out.write("     var idDocTipo = $(\"#tipo-doc\").val();\n");
      out.write("\n");
      out.write("     var combo = document.getElementById(\"tipo-doc\");\n");
      out.write("     var selected = combo.options[combo.selectedIndex].innerText;\n");
      out.write("     $(\"#tipo-doc option:selected\").remove();\n");
      out.write("\n");
      out.write("     $('.table-documents > tbody').append('<tr><td>' + selected + '</td><td>' + $(\".name-file\").text() + '</td><td><button id=' + msg + ' class=borrar onclick=eliminarFilaDocumentos(' + idDocTipo + '),deleteRow(this),deleteFile(this.id)  style=background-color:#ff4c3d  >Eliminar</button></td></tr>');\n");
      out.write("     $(\"#label-doc\").show();\n");
      out.write("     $(\".name-file\").text(\"\");\n");
      out.write("     $(\".input-file\").val(\"\");\n");
      out.write("\n");
      out.write("     } else {\n");
      out.write("\n");
      out.write("     alertError(\"Porfavor cargue un archivo.\");\n");
      out.write("\n");
      out.write("     }\n");
      out.write("\n");
      out.write("\n");
      out.write("     },\n");
      out.write("     error: function(msg) {\n");
      out.write("     alert(\"no funcion\");\n");
      out.write("     }\n");
      out.write("     });\n");
      out.write("     });*/\n");
      out.write("\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
