/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-04-12 16:08:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Registros;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import VO.CiudadVO;
import DAO.CiudadDAO;
import Model.VO.DepartamentoVO;
import DAO.DepartamentoDAO;
import VO.TipoDocumentoVO;
import java.util.ArrayList;
import java.util.ArrayList;
import DAO.TipoDocumentoDAO;
import DAO.TipoDocumentoDAO;

public final class registroDocentes_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("DAO.DepartamentoDAO");
    _jspx_imports_classes.add("VO.TipoDocumentoVO");
    _jspx_imports_classes.add("VO.CiudadVO");
    _jspx_imports_classes.add("DAO.CiudadDAO");
    _jspx_imports_classes.add("DAO.TipoDocumentoDAO");
    _jspx_imports_classes.add("Model.VO.DepartamentoVO");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("    $(document).ready(function() {\n");
      out.write("\n");
      out.write("\n");
      out.write("        $(\"#getFunc\").val(\"\" + $(\"#tipoFuncionario\").val() + \"\");\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(function() {\n");
      out.write("        var fecha = new Date();\n");
      out.write("        $(\"#datepicker\").datepicker({\n");
      out.write("\n");
      out.write("            dateFormat: 'yy-mm-dd',\n");
      out.write("            changeMonth: true,\n");
      out.write("            changeYear: true,\n");
      out.write("            yearRange: \"1950:\" + fecha.getFullYear()\n");
      out.write("        });\n");
      out.write("    }\n");
      out.write("    );\n");
      out.write("</script>\n");
      out.write("<div class=\"form-docente\">\n");
      out.write("    <div class=\"alerta alerta-doc\" hidden>\n");
      out.write("        No se ha cargado el documento.\n");
      out.write("    </div>\n");
      out.write("\n");
      out.write("    <div class=\"alerta alerta-inst\">\n");
      out.write("        Todos los campos deben estar completos\n");
      out.write("    </div>\n");
      out.write("    <div class=\"datos-principales\">\n");
      out.write("\n");
      out.write("        <form id=\"formularioFuncionario\"  action=\"ServletMainController\" method=\"post\" >\n");
      out.write("            <input name=\"modulo\" value=\"registrarFuncionario\" hidden=\"\"/>\n");
      out.write("            <input name=\"tipoFunc\" type=\"text\" id=\"getFunc\" value=\"0\" hidden=\"\"/>\n");
      out.write("            <fieldset>\n");
      out.write("                <legend>Datos Personales</legend>\n");
      out.write("                <table>\n");
      out.write("                    <thead>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Primer nombre</th>\n");
      out.write("                            <th>Segundo nombre</th>\n");
      out.write("                            <th>Primer apellido</th>\n");
      out.write("                            <th>Segundo apellido</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><input type=\"text\" name=\"pNombreFuncionario\" required></td>\n");
      out.write("                            <td><input type=\"text\" name=\"sNombreFuncionario\"></td>\n");
      out.write("                            <td><input type=\"text\" name=\"pApellidoFuncionario\" required></td>\n");
      out.write("                            <td><input type=\"text\" name=\"sApellidoFuncionario\" required></td>\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("\n");
      out.write("                </table>\n");
      out.write("                <br>\n");
      out.write("                <table>\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Tipo de documento</th>\n");
      out.write("                            <th>Numero de documento</th>\n");
      out.write("                            <th>Fecha de nacimiento</th>\n");
      out.write("                            <th>Genero</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><select name=\"tipoDocumentoFuncionario\" id=\"\" required>\n");
      out.write("\n");
      out.write("                                    ");
 TipoDocumentoDAO tipoDocumentoDAO = new TipoDocumentoDAO();
                                        ArrayList<TipoDocumentoVO> tidoVo = tipoDocumentoDAO.obtenerTipoDocumento();
                                        for (TipoDocumentoVO datosTido : tidoVo) {
                                    
      out.write("\n");
      out.write("                                    <option value=\"");
      out.print(datosTido.getTIDO_ID());
      out.write('"');
      out.write('>');
      out.print(datosTido.getTIDO_NOMBRE());
      out.write("</option>\n");
      out.write("                                    ");


                                        }

                                    
      out.write("\n");
      out.write("\n");
      out.write("                                </select></td>\n");
      out.write("                            <td><input type=\"number\" name=\"numDocumentoFuncionario\" required</td>\n");
      out.write("                            <td><input type=\"text\" id=\"datepicker\" name=\"fechaNacimientoFuncionario\" required></td>\n");
      out.write("                            <td><select name=\"generoFuncionario\" id=\"\" required>\n");
      out.write("                                    <option>MASULINO</option>\n");
      out.write("                                    <option>FEMENINO</option>\n");
      out.write("                                </select></td>\n");
      out.write("                        </tr>\n");
      out.write("                    <tbody>\n");
      out.write("\n");
      out.write("\n");
      out.write("                </table>\n");
      out.write("                <br>\n");
      out.write("                <table>\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Dep de nacimiento</th>\n");
      out.write("                            <th>Ciudad de nacimiento</th>\n");
      out.write("                            <th>Direccion</th>\n");
      out.write("                            <th>Estrato</th>\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><select name=\"depNacimientoFuncionario\" id=\"depNacimientoFuncionario\" onchange=\"cargarCiudadesXDep(this.value, this.id)\"required >\n");
      out.write("                                    <option>Seleccione...</option>\n");
      out.write("                                    ");
 DepartamentoDAO dep = new DepartamentoDAO();
                                        ArrayList<DepartamentoVO> deps = dep.obtenerDepartamentos();
                                        System.out.println(deps.size());
                                        for (DepartamentoVO datos : deps) {
                                    
      out.write("\n");
      out.write("                                    <option value=\"");
      out.print(datos.getDEPA_ID());
      out.write('"');
      out.write('>');
      out.print(datos.getDEPA_NOMBRE());
      out.write("</option>\n");
      out.write("                                    ");

                                        }
                                    
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                </select></td>\n");
      out.write("                            <td><select name=\"ciuNacimientoFuncionario\" id=\"ciudsFuncionario\" required></select></td>\n");
      out.write("                            <td><input type=\"text\" name=\"dirFuncionario\" required></td>\n");
      out.write("                            <td><select name=\"estratoFuncionario\" id=\"\" required>\n");
      out.write("                                    <option>1</option>\n");
      out.write("                                    <option>2</option>\n");
      out.write("                                    <option>3</option>\n");
      out.write("                                    <option>4</option>\n");
      out.write("                                    <option>5</option>\n");
      out.write("                                    <option>6</option>\n");
      out.write("                                    <option>7</option>\n");
      out.write("                                </select></td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("                <br>\n");
      out.write("                <table >\n");
      out.write("                    <thead>\n");
      out.write("                        <tr>\n");
      out.write("                            <th>Eps</th>\n");
      out.write("                            <th>Barrio</th>\n");
      out.write("                            <th>Ciudad de residencia</th>\n");
      out.write("                            <th>Telefono</th>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><input type=\"text\" name=\"epsFuncionario\" required></td>\n");
      out.write("                            <td><input type=\"text\" name=\"barrioFuncionario\" required></td>\n");
      out.write("                            <td><select name=\"ciuResidenciaFuncionario\" required>\n");
      out.write("\n");
      out.write("                                    ");
 CiudadDAO ciudadDAO = new CiudadDAO();
                                        ArrayList<CiudadVO> ciudadVO = ciudadDAO.obtenerCiudadesTodas();
                                        for (CiudadVO dato : ciudadVO) {
                                    
      out.write("\n");
      out.write("                                    <\n");
      out.write("                                    <option value=\"");
      out.print(dato.getCIUD_ID());
      out.write('"');
      out.write('>');
      out.print(dato.getCIUD_NOMBRE());
      out.write("</option>\n");
      out.write("                                    ");


                                        }


                                    
      out.write("\n");
      out.write("                                </select></td>\n");
      out.write("                            <td><input type=\"number\" name=\"telFuncionario\"  required /></td>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("                <button  type=\"button\" class=\"green-color-button\" onclick=\"registrarFuncionario()\" style=\"background-color: #2c7eea; padding: 15px; float: right;\" ><img src=\"Icons/arrow-alt-circle-right.svg\" style=\"width: 20px; height: 20px; margin-right:  15px; margin-top: -4px; vertical-align: middle\" >CONTINUAR</button>\n");
      out.write("            </fieldset>\n");
      out.write("\n");
      out.write("        </form>\n");
      out.write("    </div>\n");
      out.write("    <div class=\"datos-profesionales\" >\n");
      out.write("\n");
      out.write("        <br><br>\n");
      out.write("\n");
      out.write("        <fieldset>\n");
      out.write("            <legend>Informacion Profesional </legend>\n");
      out.write("            <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <th style=\"font-size: 18px; background-color: #2c7eea;; padding: 8px; color: white; border-radius: 3px;\">Estudios realizados</th>\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("            <br>\n");
      out.write("            <form enctype=\"multipart/form-data\" action=\"ServletMainController\" id=\"documentosTitulos\" method=\"POST\">\n");
      out.write("                <table class=\"table-estudios-docente est-doc\" id=\"tableEstudciosDocente\">\n");
      out.write("                    <thead>\n");
      out.write("                    <th>Titulo</th>\n");
      out.write("                    <th>Estudio</th>\n");
      out.write("                    <th>Intitucion/Universidad</th>\n");
      out.write("                    <th>Soporte</th>\n");
      out.write("                    <th></th>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr  class=\"tr-options-docente\"><td><select name=\"tipo-documento\"  id=\"titulo-doc\">\n");
      out.write("                                    <option value=\"1\" >TECNICO</option>\n");
      out.write("                                    <option value=\"2\">TECNOLOGO</option>\n");
      out.write("                                    <option value=\"3\">PROFESIONAL</option>\n");
      out.write("                                    <option value=\"4\">ESPECIALISACION</option>\n");
      out.write("                                    <option value=\"5\">MAGISTER</option>\n");
      out.write("                                    <option value=\"6\">DOCTORADO</option>\n");
      out.write("\n");
      out.write("\n");
      out.write("                                </select></td>\n");
      out.write("                            <td><input placeholder=\"Nombre del estudio\" id=\"estudio-doc\" type=\"text\"></td>\n");
      out.write("                            <td><input placeholder=\"Universidad\" id=\"uniIns\" type=\"text\"></td>\n");
      out.write("                            <td>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                <input id=\"input-file\"  class=\"input-file\" name=\"uploadedfile\" type=\"file\" />\n");
      out.write("                                <label id=\"label-doc\" class=\"blue-color-button\" for=\"input-file\"> <img src=\"Icons/file-pdf.svg\" style=\"width: 17px; height: 17px; margin-right:  5px;  margin-top: -4px; vertical-align: middle\" >Cargar Archivo</label>\n");
      out.write("                                <input type=\"text\" name=\"modulo\" value=\"subirArchivo\" hidden>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td><button type=\"button\" class=\"green-color-button\" onclick=\"agregarFilasTablaEstudiosDocente()\"> <img src=\"Icons/layer-plus.svg\" style=\"width: 17px; height: 17px; margin-right:  5px;  margin-top: -4px; vertical-align: middle\" >Agregar</button></td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("\n");
      out.write("                </table>\n");
      out.write("            </form>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <br>\n");
      out.write("            <br>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <table>\n");
      out.write("                <th style=\"font-size: 18px; background-color: #2c7eea; padding: 8px; color: white; border-radius: 3px;\">Experiencia laboral</th>\n");
      out.write("\n");
      out.write("            </table>\n");
      out.write("            <br>\n");
      out.write("            <form enctype=\"multipart/form-data\" action=\"\" method=\"POST\">\n");
      out.write("                <table class=\"table-trabajo-docente exp-doc\">\n");
      out.write("                    <thead>\n");
      out.write("\n");
      out.write("                    <th>Empresa</th>\n");
      out.write("                    <th>Cargo</th>\n");
      out.write("                    <th>Tiempo laborado</th>\n");
      out.write("                    <th>Soporte</th>\n");
      out.write("                    <th></th>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr class=\"tr-options-docente-lab\"><td>\n");
      out.write("                                <input placeholder=\"NOMBRE DE LA EMPRESA\" name=\"empresa-doc\" id=\"empresa-doc\"/></td>\n");
      out.write("                            <td><input placeholder=\"NOMBRE DEL CARGO\" id=\"cargo-doc\" type=\"text\"></td>\n");
      out.write("                            <td><input placeholder=\"TIEMPO LABORADO\" id=\"tiempo-doc\" type=\"text\"></td>\n");
      out.write("                            <td>\n");
      out.write("\n");
      out.write("                                <span class=\"input-file-exp\"></span>\n");
      out.write("\n");
      out.write("                                <input id=\"input-file-exp\"  name=\"uploadedfile\" type=\"file\" />\n");
      out.write("                                <label id=\"label-doc-exp\"class=\"blue-color-button\" for=\"input-file-exp\"><img src=\"Icons/file-pdf.svg\" style=\"width: 17px; height: 17px; margin-right:  5px;  margin-top: -4px; vertical-align: middle\" >Cargar Archivo</label>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td><button class=\"green-color-button\" onclick=\"agregarFilasTablaExperienciaDoc()\"><img src=\"Icons/layer-plus.svg\" style=\"width: 17px; height: 17px; margin-right:  5px;  margin-top: -4px; vertical-align: middle\" >Agregar</button></td>\n");
      out.write("                        </tr>\n");
      out.write("                    </tbody>\n");
      out.write("\n");
      out.write("                </table>\n");
      out.write("            </form>\n");
      out.write("        </fieldset>\n");
      out.write("    </div>\n");
      out.write("    <br>\n");
      out.write("    <br>\n");
      out.write("    <fieldset>\n");
      out.write("        <legend>AsignaciÃ³n de cursos y materias</legend>\n");
      out.write("\n");
      out.write("    </fieldset>\n");
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("\n");
      out.write("\n");
      out.write("    /*  $(\"#input-file\").change(function() {\n");
      out.write("\n");
      out.write("     var filename = $(this).val().split('\\\\').pop();\n");
      out.write("     var idname = $(this).attr('id');\n");
      out.write("     console.log($(this));\n");
      out.write("     console.log(filename);\n");
      out.write("     console.log(idname);\n");
      out.write("     $(\"#label-doc\").hide();\n");
      out.write("     $(\".input-file\").html(filename);\n");
      out.write("\n");
      out.write("     });*/\n");
      out.write("\n");
      out.write("    $(\".input-file\").change(function() {\n");
      out.write("\n");
      out.write("\n");
      out.write("        var filename = $(this).val().split('\\\\').pop();\n");
      out.write("\n");
      out.write("        var extencion = filename.substring(filename.lastIndexOf(\".\"));\n");
      out.write("\n");
      out.write("        if (extencion === \".pdf\") {\n");
      out.write("\n");
      out.write("            var idname = $(this).attr('name');\n");
      out.write("            console.log($(this));\n");
      out.write("            console.log(filename);\n");
      out.write("            console.log(idname);\n");
      out.write("\n");
      out.write("            $(\"#label-doc\").text(filename);\n");
      out.write("        } else {\n");
      out.write("            $(\".input-file\").val(\"\");\n");
      out.write("            alertError(\"El archivo debe ser formato <b>PDF</b>\");\n");
      out.write("\n");
      out.write("        }\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    $(\"#input-file-exp\").change(function() {\n");
      out.write("\n");
      out.write("        var filename = $(this).val().split('\\\\').pop();\n");
      out.write("        var idname = $(this).attr('id');\n");
      out.write("        console.log($(this));\n");
      out.write("        console.log(filename);\n");
      out.write("        console.log(idname);\n");
      out.write("        $(\"#label-doc-exp\").hide();\n");
      out.write("        $(\".input-file-exp\").html(filename);\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
