/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-12-22 18:07:47 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Secretaria;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Boletin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>Boletin Estudiantil</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"estilosboletin.css\">\n");
      out.write("        \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("          <section id=\"secion\">\n");
      out.write("\n");
      out.write("              <div id=\"opci\">\n");
      out.write("            <div class=\"articulosuperior\" >\n");
      out.write("\n");
      out.write("                <h2 id=\"titulo\"> Escoger Curso </h2> \n");
      out.write("                <select id=\"curso\" name=\"curso\" > \n");
      out.write("                    <OPTION > Cursos</option>\n");
      out.write("                    <OPTION> primero</option>\n");
      out.write("                    <OPTION> segundo</option>\n");
      out.write("                    <OPTION> tercero</option>\n");
      out.write("                    <OPTION> cuarto</option>\n");
      out.write("                    <OPTION> quinto</option>\n");
      out.write("                    <OPTION> sexto</option>\n");
      out.write("                    <OPTION> septimo</option>\n");
      out.write("                </select>     \n");
      out.write("            </div>\n");
      out.write("            <div id=\"articulo1\">\n");
      out.write("                <h2 id=\"loca3\"> Escoger Estudiante </h2> \n");
      out.write("                <select id=\"estudi\" name=\"curso\" > \n");
      out.write("                    <OPTION > Estudiantes</option>\n");
      out.write("                    <OPTION> antoniooro</option>\n");
      out.write("                    <OPTION> pedtido</option>\n");
      out.write("                    <OPTION> carloro</option>\n");
      out.write("                    <OPTION> josueo</option>\n");
      out.write("                    <OPTION> federioco</option>\n");
      out.write("                    <OPTION> daniel</option>\n");
      out.write("                    <OPTION> antoni</option>\n");
      out.write("                </select>      \n");
      out.write("            </div>\n");
      out.write("              \n");
      out.write("               <div id=\"articulo2\">\n");
      out.write("                <h2 id=\"log3\"> Escoger Periodo </h2> \n");
      out.write("                <select id=\"periodo\" name=\"curso\" > \n");
      out.write("                    <OPTION > Periodos</option>\n");
      out.write("                    <OPTION> primero</option>\n");
      out.write("                    <OPTION> segundo</option>\n");
      out.write("                    <OPTION> tercero</option>\n");
      out.write("                    <OPTION> cuarto</option>\n");
      out.write("                    <OPTION> quinto</option>\n");
      out.write("                </select>      \n");
      out.write("            </div>\n");
      out.write("              </div>\n");
      out.write("              \n");
      out.write("          </section>\n");
      out.write("               <center> <hr width=\"90%\" color=\" #F25C10\" > </center>\n");
      out.write("               \n");
      out.write("               <article id=\"articulo3\">\n");
      out.write("                  <figure>\n");
      out.write("                      <img id=\"boltin2 \"src=\"../Imagebes/boletin01.jpg\" width=\"598\" height=\"392\">\n");
      out.write("                       </figure>\n");
      out.write("                      \n");
      out.write("               \n");
      out.write("                   </article>\n");
      out.write("               \n");
      out.write("                   <div id=\"boton1\">\n");
      out.write("                       <button id=\"imprimir\" type=\"button\" name=\"Imprimir\"><a href=\"\"> Imprimir Boletin </a></button>\n");
      out.write("                   </div>\n");
      out.write("               \n");
      out.write("               <div id=\"boton2\">\n");
      out.write("                       <button id=\"imprimir\" type=\"button\" name=\"Imprimir\"><a href=\"\"> Guardar </a></button>\n");
      out.write("                   </div>\n");
      out.write("                <article id=\"articulo4\">\n");
      out.write("                    <div>\n");
      out.write("                         <figure>\n");
      out.write("                      <img id=\"imprimir2 \"src=\"../Imagebes/impresora2.png\" width=\"134\" height=\"130\">\n");
      out.write("                       </figure>\n");
      out.write("                    </div>\n");
      out.write("                </article>\n");
      out.write("               \n");
      out.write("               <article id=\"articulo5\">\n");
      out.write("                    <div>\n");
      out.write("                         <figure>\n");
      out.write("                      <img id=\"imprimir2 \"src=\"../Imagebes/guardar2.png\" width=\"90\" height=\"90\">\n");
      out.write("                       </figure>\n");
      out.write("                    </div>\n");
      out.write("                </article>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
