/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-12-22 18:08:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Secretaria;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class PerfilAlumno_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <link rel=\"stylesheet\" href=\"misestilos.css\"/>\n");
      out.write("    <head>\n");
      out.write("        <title>Perfil Alumno</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("\n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("\n");
      out.write("        <header>\n");
      out.write("\n");
      out.write("            <div> <h1> Registro Alumno </h1> </div>\n");
      out.write("            <HR align=\"left\" size=\"2\" width=\"800\" color=\"Orange\" >\n");
      out.write("\n");
      out.write("        </header>\n");
      out.write("\n");
      out.write("        <section>\n");
      out.write("            <article id=\"foto_alumno\">\n");
      out.write("\n");
      out.write("                <img src=\"IMAGENES/descarga.png\" > \n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            </article>\n");
      out.write("\n");
      out.write("            <article  id=\"datos_alumno1\">\n");
      out.write("                <form>\n");
      out.write("\n");
      out.write("                    <div id=\"nombres\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <table border=\"0\" >\n");
      out.write("                            <tbody>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>  <label>Primer Nombre </label> </td>\n");
      out.write("\n");
      out.write("                                    <td>\n");
      out.write("                                        <label>Segundo Nombre</label></td>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("\n");
      out.write("                                <tr>\n");
      out.write("                                    <td> <input type=\"text\" name=\"Primer nombre\" required=\"requiered\"> </td>\n");
      out.write("\n");
      out.write("                                    <td>  <input type=\"text\" name=\"Segundo Nombre\" required>\n");
      out.write("                                    </td>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>  <label>Primer Apellido </label> </td>\n");
      out.write("\n");
      out.write("                                    <td>\n");
      out.write("                                        <label>Segundo Apellido</label></td>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>    <input type=\"Primer Apellido\" name=\"Primer Apellido\" required></td>\n");
      out.write("\n");
      out.write("                                    <td><input type=\"text\" name=\"Segundo Apellido\" required></input>  \n");
      out.write("                                    </td>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td>  <label>Fecha De Nacimiento</label> </td>\n");
      out.write("\n");
      out.write("                                    <td>\n");
      out.write("                                        <label>Genero </label></td>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("                                <tr>\n");
      out.write("                                    <td><div class=\"item-cont\"><input class=\"large\" data-format=\"yyyy-mm-dd\" type=\"date\" name=\"date\" placeholder=\"Fecha de Nacimiento\"/><span class=\"icon-place\"></span></div>   </td>\n");
      out.write("\n");
      out.write("                                    <td>\n");
      out.write("                                        <select name=\"Genero\" >\n");
      out.write("                                            <option>Femenino</option>\n");
      out.write("                                            <option>Masculino</option>\n");
      out.write("                                        </select>\n");
      out.write("                                    </td>\n");
      out.write("\n");
      out.write("                                </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </tbody>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </table>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("\n");
      out.write("\n");
      out.write("            </article>\n");
      out.write("\n");
      out.write("\n");
      out.write("            <article id=\"datos_alumno2\">\n");
      out.write("\n");
      out.write("\n");
      out.write("                <table>\n");
      out.write("                    <tbody>\n");
      out.write("                    <td>\n");
      out.write("                        <label>Pais de Nacimiento</label> \n");
      out.write("                    <td>\n");
      out.write("\n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("\n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("\n");
      out.write("                    </td>\n");
      out.write("                    <td>\n");
      out.write("\n");
      out.write("                    </td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td><select name=\"Selecione pais \">\n");
      out.write("                                <option>aaaaaaaaaaa</option>\n");
      out.write("                            </select>\n");
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                        <td>\n");
      out.write("\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                <table>\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Tipo de Docuento</label>\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <label>Numero de Documento</label>\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <label>Lugar de expedicion</label>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <td><label>fecha de Expedicion</label>\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><select name=\"Tipo de Documento\">\n");
      out.write("                                    <option>Cedula de Ciudadania</option>\n");
      out.write("                                    <option>Tarjeta de Identidad</option>\n");
      out.write("                                    <option>Cedula de Extranjeria</option>\n");
      out.write("                                    <option>Pasaporte</option>\n");
      out.write("                                </select>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"text\" name=\"Ndocumento\" required>\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <select name=\"Lugar de expedicion\">\n");
      out.write("                                    <option></option>\n");
      out.write("                                    <option></option>\n");
      out.write("                                    <option></option>\n");
      out.write("                                    <option></option>\n");
      out.write("                                </select>\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td><div class=\"fechaexpedi\"><label class=\"title\"></label><div class=\"item-cont\"><input class=\"large\" data-format=\"yyyy-mm-dd\" type=\"date\" name=\"date\" placeholder=\"Fecha de Epedicion\"/><span class=\"icon-place\"></span></div></div>\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("\n");
      out.write("                <table>\n");
      out.write("\n");
      out.write("                    <tbody>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Ciudad donde habita</label>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                <label>Direccion de Domicilio</label>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                <label>Barrio</label>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                <label>Estrato</label>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                <label>Telefono Fijo</label> \n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <label> Movil</label>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td>\n");
      out.write("                                <select name=\"Lugar de expedicion\">\n");
      out.write("                                    <option></option>\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"text\" name=\"barrio\" required>\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"text\" name=\"Direccion de domicilio\" required>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                <select name=\"Estrato \" >\n");
      out.write("                                    <option>1</option>\n");
      out.write("                                    <option>2</option>\n");
      out.write("                                    <option>3</option>\n");
      out.write("                                    <option>4</option>\n");
      out.write("                                    <option>5</option>\n");
      out.write("                                    <option>6</option>\n");
      out.write("                                    <option>7</option>\n");
      out.write("                                    <option>8</option>\n");
      out.write("                                    <option>9</option>\n");
      out.write("                                    <option>10</option>\n");
      out.write("                                </select>\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"text\" name=\"telefonofijo\" required>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("                            <td>\n");
      out.write("                                <input type=\"text\" name=\"movil\" required>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("\n");
      out.write("            </article>\n");
      out.write("        </section>\n");
      out.write("\n");
      out.write("        <section  id=\"datosfamilia\">\n");
      out.write("\n");
      out.write("            <article id=\"Datosfamiliares\" class=\"datosfamiliaresabierto\">\n");
      out.write("                <div id =\"botondatosfamiliares\"> <h2 align=\"center\"> Datos Familiares </h2></div>\n");
      out.write("                <HR align=\"left\" size=\"2,5\" width=\"1000\" color=\"Orange\" >\n");
      out.write("            </article>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <article id=\"datos_madre\">\n");
      out.write("\n");
      out.write("                <h3>Datos Madre</h3>\n");
      out.write("                <HR align=\"left\" size=\"2,5\" width=\"600\" color=\"Orange\" > \n");
      out.write("\n");
      out.write("                <table border=\"0\" >\n");
      out.write("                    <tbody>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Nombres</label></td>\n");
      out.write("                        </tr>                               \n");
      out.write("                        <tr>\n");
      out.write("                            <td><input type=\"text\" name=\"Primer nombre\" required>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>apellidos</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><input type=\"text\" name=\"Primer nombre\" required> </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>                        \n");
      out.write("                            <td>    <label>Fecha de nacimiento</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><div class=\"element-date\"><label class=\"title\"></label><div class=\"item-cont\"><input class=\"large\" data-format=\"yyyy-mm-dd\" type=\"date\" name=\"date\" placeholder=\"Fecha de Nacimiento\"/><span class=\"icon-place\"></span></div></div></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Tipo de Docuento</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><select name=\"Tipo de Documento\">\n");
      out.write("                                    <option>Cedula de Ciudadania</option>\n");
      out.write("                                    <option>Tarjeta de Identidad</option>\n");
      out.write("                                    <option>Cedula de Extranjeria</option>\n");
      out.write("                                    <option>Pasaporte</option>\n");
      out.write("                                </select>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Numero de Documento</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td> <input type=\"text\" name=\"Segundo Nombre\" required> </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("\n");
      out.write("                            <td> <label>Pais de Nacimiento</label> </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><select name=\"Selecione pais \">\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("\n");
      out.write("                                </select>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td> <label>Ciudad donde habita</label></td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td> <select name=\"Lugar de expedicion\">\n");
      out.write("                                    <option>Ciudad donde habita</option>\n");
      out.write("                                    <option></option>\n");
      out.write("                                    <option></option>\n");
      out.write("                                    <option></option>\n");
      out.write("\n");
      out.write("                                </select>\n");
      out.write("                            </td>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("                    <td> <label>Direccion de Domicilio</label></td>\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("                        <td><input type=\"text\" name=\"Direccion de domicilio\" required></td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td><label>Estrato</label></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td><select name=\"Estrato \">\n");
      out.write("                                <option>1</option>\n");
      out.write("                                <option>2</option>\n");
      out.write("                                <option>3</option>\n");
      out.write("                                <option>4</option>\n");
      out.write("                                <option>5</option>\n");
      out.write("                                <option>6</option>\n");
      out.write("                                <option>7</option>\n");
      out.write("                                <option>8</option>\n");
      out.write("                                <option>9</option>\n");
      out.write("                                <option>10</option>\n");
      out.write("                            </select></td>\n");
      out.write("                    </tr>\n");
      out.write("                    <tr>\n");
      out.write("                        <td>\n");
      out.write("                            <label>Telefono Fijo</label>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    <tr>     \n");
      out.write("                        <td><input type=\"text\" name=\"Telefono\" required></td>\n");
      out.write("                    <tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <tr><td>\n");
      out.write("                            <label>Movil</label>\n");
      out.write("                        </td></tr>\n");
      out.write("                    <tr><td>\n");
      out.write("                            <input type=\"text\" name=\"Movil\" required>\n");
      out.write("                        </td></tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <tr><td>\n");
      out.write("                            <label>Ocupacion</label>\n");
      out.write("                        </td></tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                    <tr>\n");
      out.write("                        <td>\n");
      out.write("                            <select name=\"Ocupacion\">\n");
      out.write("                                <option>mama de casa </option>\n");
      out.write("                                <option>recicladora</option>\n");
      out.write("                                <option>independiente</option>\n");
      out.write("                                <option>mujer de la vida alegre</option>\n");
      out.write("                                <option> no trabaja </option>\n");
      out.write("\n");
      out.write("                            </select>\n");
      out.write("                        </td>\n");
      out.write("                    </tr>\n");
      out.write("\n");
      out.write("                    </tbody>\n");
      out.write("                </table>\n");
      out.write("\n");
      out.write("            </article>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("            <article id=\"datos_padre\">\n");
      out.write("                <h3> Datos del padre</h3>\n");
      out.write("                <HR align=\"left\" size=\"2,5\" width=\"80\" color=\"Orange\" >\n");
      out.write("\n");
      out.write("\n");
      out.write("                <table border=\"0\" >\n");
      out.write("                    <tbody>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td> <label>Nombres</label></td>     \n");
      out.write("                        </tr>\n");
      out.write("                        <tr>       \n");
      out.write("                            <td><input type=\"text\" name=\"Primer nombre\" required></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>apellidos</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>  <input type=\"text\" name=\"Primer nombre\" required>  </td>\n");
      out.write("                        <tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>                                  \n");
      out.write("                            <td><label>Fecha de nacimiento</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>                                                                                               \n");
      out.write("                            <td> <div class=\"element-date\"><label class=\"title\"></label><div class=\"item-cont\"><input class=\"large\" data-format=\"yyyy-mm-dd\" type=\"date\" name=\"date\" placeholder=\"Fecha de Nacimiento\"/><span class=\"icon-place\"></span></div></div></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Tipo de Docuento</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td>           \n");
      out.write("                                <select name=\"Tipo de Documento\">\n");
      out.write("                                    <option>Cedula de Ciudadania</option>\n");
      out.write("                                    <option>Tarjeta de Identidad</option>\n");
      out.write("                                    <option>Cedula de Extranjeria</option>\n");
      out.write("                                    <option>Pasaporte</option>\n");
      out.write("                                </select>\n");
      out.write("                            </td> \n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Numero de Documento</label> </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td> <input type=\"text\" name=\"Segundo Nombre\" required></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Pais de Nacimiento</label> </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><select name=\"Selecione pais \">\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("                                    <option>aaaaaaaaaaa</option>\n");
      out.write("\n");
      out.write("                                </select>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Ciudad donde habita</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><select name=\"Lugar de expedicion\">\n");
      out.write("                                    <option></option>\n");
      out.write("                                    <option></option>\n");
      out.write("                                    <option></option>\n");
      out.write("                                    <option></option>\n");
      out.write("\n");
      out.write("                                </select></td>\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Direccion de Domicilio</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><input type=\"text\" name=\"Direccion de domicilio\" required></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Estrato</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><select name=\"Estrato \">\n");
      out.write("                                    <option>1</option>\n");
      out.write("                                    <option>2</option>\n");
      out.write("                                    <option>3</option>\n");
      out.write("                                    <option>4</option>\n");
      out.write("                                    <option>5</option>\n");
      out.write("                                    <option>6</option>\n");
      out.write("                                    <option>7</option>\n");
      out.write("                                    <option>8</option>\n");
      out.write("                                    <option>9</option>\n");
      out.write("                                    <option>10</option>\n");
      out.write("                                </select>\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td> <label>Telefono Fijo</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>        \n");
      out.write("                            <td><input type=\"text\" name=\"Telefono\" required></td>\n");
      out.write("\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Movil</label></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><input type=\"text\" name=\"Movil\" required></td>\n");
      out.write("                        </tr>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        <tr>\n");
      out.write("                            <td><label>Ocupacion</label> </td>\n");
      out.write("                        </tr>\n");
      out.write("                        <tr>\n");
      out.write("                            <td> <select name=\"Ocupacion\">\n");
      out.write("                                    <option>mama de casa </option>\n");
      out.write("                                    <option>recicladora</option>\n");
      out.write("                                    <option>independiente</option>\n");
      out.write("                                    <option>mujer de la vida alegre</option>\n");
      out.write("                                    <option> no trabaja </option>\n");
      out.write("\n");
      out.write("                                </select>\n");
      out.write("\n");
      out.write("                            </td>\n");
      out.write("                        </tr>\n");
      out.write("                   <div class=\"posibotos\">\n");
      out.write("           <a class=\"boton colorBoton formaBoton\"  target=\"central\" href=\"#\">Registrar</a>\n");
      out.write("\n");
      out.write("        </div>\n");
      out.write("            </article>\n");
      out.write("   \n");
      out.write("\n");
      out.write("</section>\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
