/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2023-05-24 23:10:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import Controller.ConexionBD;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("Controller.ConexionBD");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");

    ConexionBD con = new ConexionBD();
    con.ConexionBD();
       if (session.getAttribute("personaID") != null) {
        response.sendRedirect("paginaPrincipal.jsp");
    }



      out.write("\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"Js/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" />\n");
      out.write("        <!-- <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ\" crossorigin=\"anonymous\">\n");
      out.write("         <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\" integrity=\"sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe\" crossorigin=\"anonymous\"></script> -->\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/bootstrap/js/bootstrap.bundle.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/jquery-3.6.0.min.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" charset=\"UTF-8\" src=\"Js/controladorPrincipal.js\"></script>\n");
      out.write("        <title>JSP Page</title>\n");
      out.write("    </head>\n");
      out.write("    <body class=\"bg-dark\"\n");
      out.write("          style=\"\n");
      out.write("          overflow-x: hidden;\n");
      out.write("          background-image: url(Styles/iconos/fondo.png);\n");
      out.write("          background-size: cover;\n");
      out.write("          background-repeat: no-repeat;\n");
      out.write("          \n");
      out.write("          \">\n");
      out.write("        <div class=\"contariner\">\n");
      out.write("            <div class=\"row\">\n");
      out.write("\n");
      out.write("                <section class=\"container w-50 mt-5\">\n");
      out.write("                    <i><img onclick=\"cerrarSesion()\" title=\"Cerrar Sesión\" style=\"width: 750px; cursor: pointer\" src=\"Styles/iconos/logo.png\" alt=\"alt\"/></i>\n");
      out.write("                </section>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"row\">\n");
      out.write("                <section class=\"container w-25  p-4 mt-5 rounded shadow border bg-white shadow\" >\n");
      out.write("               \n");
      out.write("                        <div class=\"container bg-white\">\n");
      out.write("                            <h4 class=\"text-center\">Inicio Sesión</h4>\n");
      out.write("                            <br>\n");
      out.write("                            <label for=\"numeroDocumento\" class=\"\">Tipo de Usuario</label>\n");
      out.write("                            <select class=\"form-select\" id=\"tipoUsuario\">\n");
      out.write("                                <option value=\"\" selected disabled>Seleccione...</option>\n");
      out.write("                                <option value=\"1\">Propietario/Residente</option>\n");
      out.write("                                <option value=\"2\">Trabajador</option>\n");
      out.write("                                <option value=\"3\">Administrador</option>\n");
      out.write("                            </select>\n");
      out.write("                            <br>\n");
      out.write("                            <label for=\"numeroDocumentoSesion\" class=\"\">Numero Documento</label>\n");
      out.write("                            <input type=\"number\" class=\"form-control\" id=\"numeroDocumentoSesion\" name=\"numeroDocumento\">\n");
      out.write("                            <br>\n");
      out.write("                            <label for=\"password\" class=\"\">Contraseña</label>\n");
      out.write("                            <input type=\"password\" class=\"form-control\" id=\"passwordSesion\" name=\"passwordSesion\">\n");
      out.write("                            <br><br>\n");
      out.write("                            <div id=\"liveAlertPlaceholder\"></div>\n");
      out.write("                            <input type=\"text\" value=\"inicioSesion\" name=\"modulo\" hidden>\n");
      out.write("                            <button type=\"button\" onclick=\"inicioSesion()\"  class=\"btn btn-primary  float-rigth\">Inciar Sesión</button>\n");
      out.write("                            <br><br>\n");
      out.write("                            <a class=\"link-info\" style=\"cursor:  pointer\" \n");
      out.write("                               data-bs-toggle=\"modal\" data-bs-target=\"#exampleModal\">!Registra tu conjunto¡</a>\n");
      out.write("                        </div>\n");
      out.write("             \n");
      out.write("                </section>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("\n");
      out.write("        <div class=\"modal fade\" id=\"exampleModal\" tabindex=\"-1\" aria-labelledby=\"exampleModalLabel\" aria-hidden=\"true\">\n");
      out.write("            <div class=\"modal-dialog modal-lg\">\n");
      out.write("                <div class=\"modal-content\">\n");
      out.write("                    <div class=\"modal-header\">\n");
      out.write("                        <h1 class=\"modal-title fs-5\" id=\"exampleModalLabel\">Registrar Conjunto</h1>\n");
      out.write("                        <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"modal\" aria-label=\"Close\"></button>\n");
      out.write("                    </div>\n");
      out.write("                    <br>\n");
      out.write("                    <form class=\"\" action=\"MainController\" method=\"post\" id=\"formInicial\">\n");
      out.write("                        <div class=\"modal-body\">\n");
      out.write("                            <div id=\"alertaRegistro\"></div>\n");
      out.write("                            <section class=\"container\">\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-2\">\n");
      out.write("                                        <label class=\"fw-semibold\" for=\"nombreConjunto\">Nombre del Conjunto</label>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-4\">\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" name=\"nombreConjunto\" id=\"nombreConjunto\" required>\n");
      out.write("                                    </div>            \n");
      out.write("                                    <div class=\"col-2\">\n");
      out.write("                                        <label class=\"fw-semibold\" for=\"dirConjunto\">Dirección</label>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-4\">\n");
      out.write("                                        <input class=\"form-control\" type=\"text\" name=\"dirConjunto\" id=\"dirConjunto\" required>\n");
      out.write("                                    </div>   \n");
      out.write("\n");
      out.write("                                </div>\n");
      out.write("                                <br>\n");
      out.write("\n");
      out.write("                                <h5>Información Adminstrador</h5>\n");
      out.write("                                <br>\n");
      out.write("\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-2\">\n");
      out.write("                                        <label for=\"numDocumento\" class=\"fw-semibold\">Numero de Documento</label>\n");
      out.write("                                    </div> \n");
      out.write("                                    <div class=\"col-4\">\n");
      out.write("                                        <input type=\"number\" class=\"form-control\" name=\"numeroDocumento\" id=\"numDocumento\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <br>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-2\">\n");
      out.write("                                        <label for=\"priNombre\" class=\"fw-semibold\">Primer Nombre</label>\n");
      out.write("                                    </div> \n");
      out.write("                                    <div class=\"col-4\">\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" name=\"primerNombre\" id=\"priNombre\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-2\">\n");
      out.write("                                        <label class=\"fw-semibold\" for=\"segNombre\">Segundo Nombre</label>\n");
      out.write("                                    </div> \n");
      out.write("                                    <div class=\"col-4\">\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" name=\"segundoNombre\" id=\"segNombre\">\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <br>\n");
      out.write("                                <div class=\"row\">\n");
      out.write("                                    <div class=\"col-2\">\n");
      out.write("                                        <label class=\"fw-semibold\"  for=\"priApellido\">Primer Apellido</label>\n");
      out.write("                                    </div> \n");
      out.write("                                    <div class=\"col-4\">\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" name=\"primerApellido\" id=\"priApellido\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-2\">\n");
      out.write("                                        <label class=\"fw-semibold\"  for=\"segApellido\">Segundo Apellido</label>\n");
      out.write("                                    </div> \n");
      out.write("                                    <div class=\"col-4\">\n");
      out.write("                                        <input type=\"text\" class=\"form-control\" name=\"segundoApellido\" id=\"segApellido\" >\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("                                <br>\n");
      out.write("                                <div class=\"row\" id=\"rowPassword\">\n");
      out.write("                                    <br>\n");
      out.write("                                    <div class=\"col-2\">\n");
      out.write("                                        <label class=\"fw-semibold\"  for=\"password\">Contraseña</label>\n");
      out.write("                                    </div> \n");
      out.write("                                    <div class=\"col-4\">\n");
      out.write("                                        <input type=\"password\" class=\"form-control\" name=\"password\" id=\"password\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                    <div class=\"col-2\">\n");
      out.write("                                        <label class=\"fw-semibold\"  for=\"confPassword\">Confirmar</label>\n");
      out.write("                                    </div> \n");
      out.write("                                    <div class=\"col-4\">\n");
      out.write("                                        <input type=\"password\" class=\"form-control\" name=\"confPassword\" id=\"confPassword\" required>\n");
      out.write("                                    </div>\n");
      out.write("                                </div>\n");
      out.write("\n");
      out.write("                            </section>\n");
      out.write("                            <input type=\"text\" name=\"modulo\" value=\"registrarConjunto\" hidden>\n");
      out.write("\n");
      out.write("\n");
      out.write("                        </div>\n");
      out.write("                        <div class=\"modal-footer\">               \n");
      out.write("                            <button type=\"submit\" class=\"btn btn-primary\">Guardar</button>\n");
      out.write("                        </div>\n");
      out.write("                    </form>\n");
      out.write("                </div>\n");
      out.write("            </div>\n");
      out.write("        </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<script>\n");
      out.write("// FUNCION AJAX PARA ENVIAR DATOS DE REGISTRO AL CONTROLADOR DE CONJUNTO Y ADMINISTRADOR\n");
      out.write("    $(\"#formInicial\").submit(function (e) {\n");
      out.write("        e.preventDefault();\n");
      out.write("        let data = \"\";\n");
      out.write("        let url = \"\";\n");
      out.write("        url = $(\"#formInicial\").attr('action'); // Tomamos la url del action\n");
      out.write("        data = $(\"#formInicial\").serialize(); // serializamos todos los campos del formulario      \n");
      out.write("\n");
      out.write("        $.ajax({\n");
      out.write("            type: 'post', // lo enviamos por el metodo post\n");
      out.write("            url: url, // url del controlador\n");
      out.write("            data: data, // datos serializados del formulario\n");
      out.write("            success: function (data) {\n");
      out.write("                $(\"#formInicial\")[0].reset();\n");
      out.write("                $(\"#alertaRegistro\").append(`<div class=\"alert alert-success alert-dismissible\" role=\"alert\">\n");
      out.write("       <div>¡Registro Exitoso!</div>\n");
      out.write("       <button type=\"button\" class=\"btn-close\" data-bs-dismiss=\"alert\" aria-label=\"Close\"></button>\n");
      out.write("    </div>`);\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("    });\n");
      out.write("\n");
      out.write("    // FUNCION AJAX PARA ENVIAR DATOS DE REGISTRO AL CONTROLADOR DE CONJUNTO Y ADMINISTRADOR\n");
      out.write("    $(\"#formInicoSesion\").submit(function (e) {\n");
      out.write("    e.preventDefault();\n");
      out.write("        let data = \"\";\n");
      out.write("        let url = \"\";\n");
      out.write("        url = $(\"#formInicioSesion\").attr('action'); // Tomamos la url del action\n");
      out.write("        data = $(\"#formInicioSesion\").serialize(); // serializamos todos los campos del formulario     \n");
      out.write("     \n");
      out.write("        $.ajax({\n");
      out.write("            type: 'post', // lo enviamos por el metodo post\n");
      out.write("            url: url, // url del controlador\n");
      out.write("            data: data, // datos serializados del formulario\n");
      out.write("            success: function (data) {\n");
      out.write("                let verificacionSesion = parseInt(data);\n");
      out.write("                if (verificacionSesion === 1) {\n");
      out.write("                    window.location.replace(\"paginaPrincipal.jsp\");\n");
      out.write("                }\n");
      out.write("\n");
      out.write("            }\n");
      out.write("        });\n");
      out.write("\n");
      out.write("    });\n");
      out.write("</script>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
