/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.60
 * Generated at: 2022-12-22 18:05:50 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.Docente;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class infGeneralDoc_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("    <head>\n");
      out.write("        <title>TODO supply a title</title>\n");
      out.write("        <meta charset=\"UTF-8\">\n");
      out.write("        <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
      out.write("        <link rel=\"stylesheet\" href=\"estilosInfDoc.css\">\n");
      out.write("               \n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\" src=\"tinyeditor.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" src=\"../Jquey.js\"></script>\n");
      out.write("        <script type=\"text/javascript\" >\n");
      out.write("\n");
      out.write("            function mostrarPops() {\n");
      out.write("\n");
      out.write("                $(\"#todo\").css(\"-webkit-filter\", \"blur(5px)\");\n");
      out.write("\n");
      out.write("                $(\"#popu\").fadeIn()('fast');\n");
      out.write("\n");
      out.write("            }\n");
      out.write("            function ocultarPops() {\n");
      out.write("\n");
      out.write("                $(\"#todo\").css(\"-webkit-filter\", \"blur(0px)\");\n");
      out.write("\n");
      out.write("                $(\"#popu\").fadeOut()('fast');\n");
      out.write("\n");
      out.write("            }\n");
      out.write("\n");
      out.write("\n");
      out.write("        </script>       \n");
      out.write("    </head>\n");
      out.write("    <body>\n");
      out.write("       <div id=\"todo\">\n");
      out.write("        <header id=\"opci\">\n");
      out.write("            <h1>INFORMACION</h1>\n");
      out.write("            \n");
      out.write("               <button   id=\"Pops\" type=\"button\" name=\"pop\" onclick=\"mostrarPops()\">Publicar</button>\n");
      out.write("            \n");
      out.write("            \n");
      out.write("        </header>\n");
      out.write("        <div>\n");
      out.write("            <div id=\"articulo1\" >\n");
      out.write("            <article>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("            </article>\n");
      out.write("            </div>\n");
      out.write("             <div id=\"articulo2\">\n");
      out.write("            <article>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("            </article>\n");
      out.write("            </div>\n");
      out.write("             <div id=\"articulo3\">\n");
      out.write("            <article>\n");
      out.write("                \n");
      out.write("              \n");
      out.write("            </article>\n");
      out.write("            </div>\n");
      out.write("          \n");
      out.write("               \n");
      out.write("            </div>\n");
      out.write("            \n");
      out.write("         \n");
      out.write("            \n");
      out.write("        </div>\n");
      out.write("       \n");
      out.write("         <div id=\"popu\" hidden=\"hidden\">\n");
      out.write("                <div id=\"pop\">\n");
      out.write("                     \n");
      out.write("                    <div id=\"cabe\"></div>\n");
      out.write("                    \n");
      out.write("                    <h1 id=\"popt\">HACER PUBLICACION</h1>\n");
      out.write("                    <a id=\"cerrar\" onclick=\"ocultarPops()\">Cerrar</a>\n");
      out.write("                <a id=\"guardar\" onclick=\"ocultarPops()\">Publicar</a>\n");
      out.write("                \n");
      out.write("                <textarea id=\"input\" style=\"width:450px; height:200px\"></textarea>\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("new TINY.editor.edit('editor',{\n");
      out.write("	id:'input',\n");
      out.write("	width:584,\n");
      out.write("	height:175,\n");
      out.write("	cssclass:'te',\n");
      out.write("	controlclass:'tecontrol',\n");
      out.write("	rowclass:'teheader',\n");
      out.write("	dividerclass:'tedivider',\n");
      out.write("	controls:['bold','italic','underline','strikethrough','|','subscript','superscript','|',\n");
      out.write("			  'orderedlist','unorderedlist','|','outdent','indent','|','leftalign',\n");
      out.write("			  'centeralign','rightalign','blockjustify','|','unformat','|','undo','redo','n',\n");
      out.write("			  'font','size','style','|','image','hr','link','unlink','|','cut','copy','paste','print'],\n");
      out.write("	footer:true,\n");
      out.write("	fonts:['Verdana','Arial','Georgia','Trebuchet MS'],\n");
      out.write("	xhtml:true,\n");
      out.write("	cssfile:'style.css',\n");
      out.write("	bodyid:'editor',\n");
      out.write("	footerclass:'tefooter',\n");
      out.write("	toggle:{text:'show source',activetext:'show wysiwyg',cssclass:'toggle'},\n");
      out.write("	resize:{cssclass:'resize'}\n");
      out.write("});\n");
      out.write("</script>\n");
      out.write("                \n");
      out.write("                \n");
      out.write("                </div>\n");
      out.write("                    \n");
      out.write("                    \n");
      out.write("                  \n");
      out.write("                   \n");
      out.write("                </div>\n");
      out.write("    </body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
